### ISSUE TITLE
米游社cookie

### ISSUE THREAD

**Issue by MiniGrayGay** [SilveryStar/Adachi-BOT#1]
昨天米游社做了更新，限制每个cookie只能查询30次，机器人能不能支持填入多个cookie，然后每个cookie轮流用呢

**Comment by SilveryStar** [comment]
> 昨天米游社做了更新，限制每个cookie只能查询30次，机器人能不能支持填入多个cookie，然后每个cookie轮流用呢

（其实一直在TODO里只是咕了）近期会进行更新
