### ISSUE TITLE
询问，关于QQ频道

### ISSUE THREAD

**Issue by Fahaxikiii** [SilveryStar/Adachi-BOT#101]
### 系统版本

Windows Server 2012 R2 DataCenter 64bitCN

### Node.js 版本

16.13.0

### 应用版本

2.1.6

### 复述操作

机器人不能收到来自QQ频道的消息吗？我的机器人已经加入频道。

### 错误报告

```Text
无
```

**Comment by SilveryStar** [comment]
不能，qq 频道目前好像也没进入正式公测，要获取频道信息也只能等上游 oicq 出了相关功能我这才能处理

**Comment by Fahaxikiii** [comment]
好的好的
