### ISSUE TITLE
圣遗物强化文字位置偶现异常

### ISSUE THREAD

**Issue by Accelerator1213** [SilveryStar/Adachi-BOT#111]
### 系统版本

 centos_8_0_x64

### Node.js 版本

13.13.0

### 应用版本

2.2.0

### 启动方式

Docker

### 复述操作

#art

![image](https://user-images.githubusercontent.com/82789349/142975042-fe7c07bb-f5ce-4896-bc72-31bc7182e142.png)

另外，私人订阅的页面不可用。

![image](https://user-images.githubusercontent.com/82789349/142975139-ba47a295-b58d-4382-8ef2-c0e0fbc3d30b.png)

### 配置文件

```YAML
默认设置，仅修改了settings的账号密码与cookies的cookies。
```

### 错误报告

```Text
未发生错误报告。
```

**Comment by Accelerator1213** [comment]
![image](https://user-images.githubusercontent.com/82789349/142975176-a1a5397a-4253-4da4-b185-280df65106c6.png)

![image](https://user-images.githubusercontent.com/82789349/142975187-26ec10b9-0ddb-4837-8a09-1e3726324c8d.png)


生成位置错误的强化出来也是个错的。

看起来略微难受一些。

另外顺带问一下，私人订阅的cookies用document.cookies复制出来的提示Please Login是cookies有问题还是回复的有误？

**Comment by SilveryStar** [comment]
2.3的圣遗物因为还没加图片，所以会错位
私人订阅的话就是字面意思，你需要登录米游社原神社区，之后再去获取 `document.cookie` 才是可用的

**Comment by SilveryStar** [comment]
页面失效的之后再换，这两天很忙

**Comment by Accelerator1213** [comment]
已登录，能获取到Cookies，但是依旧是Please login。

![image](https://user-images.githubusercontent.com/82789349/143054162-84c5689b-1aed-46d1-9bcb-c321feef7382.png)

![image](https://user-images.githubusercontent.com/82789349/143054242-cf6c2e71-3135-4bb6-9b1b-7bcc0f8da83b.png)

**Comment by SilveryStar** [comment]
哦，你别复制外面的单引号啊23333

**Comment by Accelerator1213** [comment]
我觉得我废了23333333

![image](https://user-images.githubusercontent.com/82789349/143068912-b6463626-d5b1-4d92-a46e-a3cfe99eb78b.png)

**Comment by SilveryStar** [comment]
emmm 你这个 cookie 放 `cookies.yml` 能正常查询吗，如果不能的话就是 cookie 的问题，可以试着退出登录之后再重登一次，然后就是确定一下里面是不是有 `_MHYUUID` `ltoken` `login_uid` `ltuid` 这些，如果还不能用就不太清楚是为什么，我用最新版 docker 部署是可以正常使用的
![XNM6T123@{3YU8F)%M({7H1](https://user-images.githubusercontent.com/42149290/143177095-6ea3f394-9dab-42b5-bcd7-704fff7206d3.png)

**Comment by SilveryStar** [comment]
圣遗物素材已全部更新

**Comment by Accelerator1213** [comment]
我cookies还是挂了hhhhh，我觉得可能是我的问题，复制的内容里不包含login_uid这个内容。

**Comment by Accelerator1213** [comment]
换了个浏览器，重新登录，拉的cookie还是报错；

我把cookies.yml的cookie拿出来直接用同错。。。

![image](https://user-images.githubusercontent.com/82789349/143249436-dfae0a3f-71c1-45d8-a714-74cf1ee03827.png)

**Comment by SilveryStar** [comment]
哦哦哦我知道了，有个版本把指令改成大小写不敏感了，然后估计 cookie 是被强制转换成全小写了，所有没法用，马上改

**Comment by SilveryStar** [comment]
我的锅，现在应该是好了

**Comment by Accelerator1213** [comment]
好的，么么哒~

**Comment by Accelerator1213** [comment]
大概好了……吧……不知道其他人好了没，我还在相同的报错hhhhhhhh

**Comment by Accelerator1213** [comment]
Well done~
