### ISSUE TITLE
武器池抽卡模拟保底异常

### ISSUE THREAD

**Issue by Accelerator1213** [SilveryStar/Adachi-BOT#115]
### 系统版本

centos_8_0_x64

### Node.js 版本

13.13.0

### 应用版本

2.2.0-bugfix3

### 启动方式

Docker

### 复述操作

模拟武器池抽卡时，四星保底和五星保底异常，会出现连续歪的情况。

五星：
![L7 @$G28VY(71CDPQ(RZW5D](https://user-images.githubusercontent.com/82789349/143342397-8adc9902-7dcf-4ef8-b376-7ce020f48eea.png)

![(FEBGMA8N6Z2AW7KN_Y%K5D](https://user-images.githubusercontent.com/82789349/143342476-ada7d6ee-0e72-4f5c-9e57-2c1e51b477ce.png)

四星：

![02f0b294c08b401ccdcaac3f59fce180](https://user-images.githubusercontent.com/82789349/143342826-4ca68417-6398-4531-8466-4314e5556336.png)

BOT稳定运行之后我给丢到群里面了，bug反馈可能会多一些hhhhhh

辛苦了~

### 配置文件

```YAML
未修改cookies.yml和settings.yml以外的文件。
```

### 错误报告

```Text
无错误报告。
```

**Comment by SilveryStar** [comment]
emmm 我没太明白意思，目前是没有定规机制的，不知道你说的连续歪是不是指这个

**Comment by Accelerator1213** [comment]
四星、五星的武器UP池也遵循UP规则，即本次祈愿获得的四星道具/五星武器非当期UP武器，则通过武器活动祈愿获得的下一个四星/五星武器必定为当期UP武器。

武器池是可以有25%的概率歪出四星角色的，但不会连续歪出两个。

而通过武器活动祈愿获得的五星武器不是当期UP（本期是松籁响起之时或苍古自由之誓）武器时，下次获得的五星武器必定是当期UP武器。

**Comment by SilveryStar** [comment]
啊这，你这规则哪看的（
1. 武器不存在「本次祈愿获得的五星武器非当期UP武器，则通过武器活动祈愿获得的下一个五星武器必定为当期UP武器」的规则，要不然也不会存在棉花31本厕纸的惨案[传送门](https://www.bilibili.com/video/BV1xV411x7pS)，定规也没意义
2. 四星的话说实话懒得管，玩模拟抽卡不就图个五星XD

**Comment by Accelerator1213** [comment]
棉花当年31本厕纸也是厕纸UP的啊哈哈哈哈哈哈哈。

武器池的每次UP都是UP俩。

**Comment by SilveryStar** [comment]
哦，这样来着，那我只能说我尽力吧，祈愿的代码逻辑都是1.x版本的事了，不过不紧急，先放着吧

**Comment by Accelerator1213** [comment]
好的呢~
