### ISSUE TITLE
【公告】米游社接口更新的影响及更新情况

### ISSUE THREAD

**Issue by SilveryStar** [SilveryStar/Adachi-BOT#116]
## 公告
**米游社接口更新**
2021年12月14日 18:00:00，米游社接口对关于角色信息查询的接口进行了更新。更新后， BOT 不再能通过 UID 查询任何玩家（仅包含开放米游社数据的玩家）的任何角色的数据，而只能查询到好感最高的前八名角色。因此，未来 `silvery-star.character` 不再支持通过 UID 查询其他玩家的角色，即被移入私人服务。

**米游社版本更新**
2021年11月25日 11:00:00，米游社 App 更新至 V2.17.1版本（下称“新版本”），同时对其数据接口的查询权限进行了更新，与本项目功能相关的更新内容如下：
1. 玩家的角色数据查询：新版本接口中，对于非账号持有者本人的查询请求，只返回部分角色信息（好感最高的前八名角色）；而如果查询请求携带的 cookie 为账号持有者本人，则会返回所有信息。
2. 深渊的挑战数据查询：新版本接口中，对于非账号持有者本人的查询请求，只返回深境螺旋挑战回顾部分；而如果查询请求携带的 cookie 为账号持有者本人，则会返回所有信息。
3. 深渊中的出战次数：新版本接口中，只返回出战次数前四的角色（过去是前八）。

针对与米游社的接口更新，我们初步的提出以下方案进行应对：
1. 将 `silvery-star.mys-query`, `silvery-star.abyss` 功能转移至私人服务
2. 保留 `silvery-star.uid-query` 功能，并使用新的样式卡片

此 issue 用于讨论由于米游社新版本接口更新产生的相关问题，如果你有更好的想法，欢迎评论交流

**更新情况**
2021年11月28日 00:00:04，本项目更新至 v2.2.1 版本，并就以上涉及的功能的指令进行了如下改动：
1. 指令 `silvery-star.mys-query` 和 `silvery-star.abyss` 被废弃
2. 指令 `silvery-star.bind` 从过去的绑定米游社通行证ID改为绑定 UID，以前的绑定信息将被废弃
3. 指令 `silvery-star.uid-query` 的参数改为与过去的 `silvery-star.mys-query` 相同，现在也可以通过 @ 或留空的方式获取信息；在之后的版本中，我们会为该指令定制新的样式
4. 指令 `silvery-star.character` 的参数改变，现在可以选择填写 UID 来指定待查询的账号，默认情况下，会查询绑定的 UID 的信息
5. 新增指令 `silvery-star.private-mys` 和 `silvery-star.private-abyss` ，这是 1. 中指令的私人服务形式

必须重新强调，本项目的私人服务功能，旨在为原神玩家提供便利，因隐私数据泄露产生的一切安全问题均为应用部署者的个人行为，与本项目无关 → [声明](https://docs.adachi.top/statement/)

## 私人服务
私人服务是我们为玩家提供的私人便利功能，包含米游社签到，便笺等功能，需要用户提供米游社 cookie 才能开启。下面简单的介绍如何开启私人服务：
1. 私聊 BOT，输入 `help` 查看帮助信息
2. 找到并使用 添加私人服务 指令，如 `ps`
3. 按照指示获取 cookie 并确定

**Comment by SilveryStar** [comment]
由于深渊数据查询被限制，深渊黑榜估计也凉了，此功能 https://github.com/SilveryStar/Adachi-BOT/issues/70#issuecomment-973865578 将不会再做考虑

**Comment by KimigaiiWuyi** [comment]
可以参考一下[我的](https://github.com/KimigaiiWuyi/GenshinUID/issues/34)
还有待测试

**Comment by SilveryStar** [comment]
> 可以参考一下[我的](https://github.com/KimigaiiWuyi/GenshinUID/issues/34) 还有待测试

这……是不是太暴力了点，就一个个的硬查吗……
在我个人层面是不太主张这么操作的，毕竟根据我对这个项目的 issue 的观察，还是有个别大群再用的，再说小群使用的风险也不低了……

说实话在这方面我甚至更倾向用户提供 cookies 来查询这条路，正好这个项目里有易扩展的方法，虽说在账户安全性方面也不太靠谱就是了

**Comment by KimigaiiWuyi** [comment]
> > 可以参考一下[我的](https://github.com/KimigaiiWuyi/GenshinUID/issues/34) 还有待测试
> 
> 这……是不是太暴力了点，就一个个的硬查吗…… 在我个人层面是不太主张这么操作的，毕竟根据我对这个项目的 issue 的观察，还是有个别大群再用的，再说小群使用的风险也不低了……
> 
> 说实话在这方面我甚至更倾向用户提供 cookies 来查询这条路，正好这个项目里有易扩展的方法，虽说在账户安全性方面也不太靠谱就是了

我也写好了警告，我的项目无所谓，因为py的pil库问题，用的人应该少，或者说没什么大群会用；
主要是两个Adachi的，大群会用的比较多，所以主要想公开出来一起考虑下该怎么办；
也许不用完全遍历，可以分组遍历，先拿到8个能拿到的，再看看御三家+国家队+主角，然后再看看怎么分组，主要是逻辑有点难判断

**Comment by MiniGrayGay** [comment]
> > > 可以参考一下[我的](https://github.com/KimigaiiWuyi/GenshinUID/issues/34) 还有待测试
> > 
> > 
> > 这……是不是太暴力了点，就一个个的硬查吗…… 在我个人层面是不太主张这么操作的，毕竟根据我对这个项目的 issue 的观察，还是有个别大群再用的，再说小群使用的风险也不低了……
> > 说实话在这方面我甚至更倾向用户提供 cookies 来查询这条路，正好这个项目里有易扩展的方法，虽说在账户安全性方面也不太靠谱就是了
> 
> 我也写好了警告，我的项目无所谓，因为py的pil库问题，用的人应该少，或者说没什么大群会用； 主要是两个Adachi的，大群会用的比较多，所以主要想公开出来一起考虑下该怎么办； 也许不用完全遍历，可以分组遍历，先拿到8个能拿到的，再看看御三家+国家队+主角，然后再看看怎么分组，主要是逻辑有点难判断

虽然是这么说，可能因为express+puppeteer？我感觉genshinuid的pil生成图片比两个adachi都要快，用了adachi也不短时间了，应该不是错觉

**Comment by SilveryStar** [comment]
> 可以参考一下[我的](https://github.com/KimigaiiWuyi/GenshinUID/issues/34) 还有待测试

欸，所以 `/game_record/app/genshin/api/character` 这个接口时不计算 cookie 使用次数的吗

**Comment by KimigaiiWuyi** [comment]
> > 可以参考一下[我的](https://github.com/KimigaiiWuyi/GenshinUID/issues/34) 还有待测试
> 
> 欸，所以 `/game_record/app/genshin/api/character` 这个接口时不计算 cookie 使用次数的吗

我写了CK锁定，一天内相同uid查询均使用同一个ck，这样肯定是不算次数的

**Comment by SilveryStar** [comment]
> 我写了CK锁定，一天内相同uid查询均使用同一个ck，这样肯定是不算次数的

嗷，那挺好
