### ISSUE TITLE
求问windows环境下如何构建

### ISSUE THREAD

**Issue by Atxoed** [SilveryStar/Adachi-BOT#122]
### 系统版本

windows 10

### Node.js 版本

v16.13.0

### 复述操作

求问一下，翻文档没看到

**Comment by SilveryStar** [comment]
不写 Windows 部署方式是因为不建议在 Windows 环境中部署，最好在 Linux 中进行，如果你一定打算部署在 Windows，参考 docker

**Comment by Atxoed** [comment]
docker是要挂虚拟机吗，查了半天不知道怎么用。。。

**Comment by VsentCN** [comment]
> docker是要挂虚拟机吗，查了半天不知道怎么用。。。

https://www.bilibili.com/read/cv13331826?from=search&spm_id_from=333.337.0.0
可以参考这个

**Comment by SilveryStar** [comment]
> https://www.bilibili.com/read/cv13331826?from=search&spm_id_from=333.337.0.0 可以参考这个

惊了，居然还有这个
不过现在的版本已经不支持在 windows 环境中使用 forever 部署了

@Atxoed 如果你还是想在 windows 中部署的话，可以参考以下 [这个](https://www.cnblogs.com/makalochen/p/14286100.html)，如果可以的话，尽可能使用 Linux 服务器，这样会方便很多，这个应用对服务器的性能要求挺低的，阿里云或者腾讯云的学生机都可以，费用也很低

**Comment by VsentCN** [comment]
> > https://www.bilibili.com/read/cv13331826?from=search&spm_id_from=333.337.0.0 可以参考这个
> 
> 惊了，居然还有这个 不过现在的版本已经不支持在 windows 环境中使用 forever 部署了
> 
> @Atxoed 如果你还是想在 windows 中部署的话，可以参考以下 [这个](https://www.cnblogs.com/makalochen/p/14286100.html)，如果可以的话，尽可能使用 Linux 服务器，这样会方便很多，这个应用对服务器的性能要求挺低的，阿里云或者腾讯云的学生机都可以，费用也很低

我就是有一台windows服务器没有利用完才部署在windows环境下，我这里直接启动也没什么问题，稳定性也不错，就没用forever启动。

**Comment by Atxoed** [comment]
啊这我已经照b站专栏去做且成功了，也就是说要重来吗。。。

**Comment by SilveryStar** [comment]
emmmm你能成功就行，那这里我就关了
