### ISSUE TITLE
询问一下guide功能的更新频率

### ISSUE THREAD

**Issue by Cn7ci4** [SilveryStar/Adachi-BOT#125]
### 系统版本

windows 11 企业版 22000.348

### Node.js 版本

17.1.0

### 应用版本

2.2.1

### 复述操作

在群里输入guide 阿贝多
![_OE5)5BV_9 BMG2RMK2061T](https://user-images.githubusercontent.com/32661244/144254802-abe1bc65-b167-4043-a354-4ef2e7b22603.gif)
目前米游社最新攻略信息为
![YWCLYZ UL5OY@JS5CCL)JSR](https://user-images.githubusercontent.com/32661244/144254885-254d457e-d730-48e3-bc7b-16a042697cec.jpg)

### 配置文件

```YAML
无相关信息
```

### 错误报告

```Text
无
```

**Comment by SilveryStar** [comment]
频率:我想起来就更新（捂脸）

**Comment by SilveryStar** [comment]
更了

**Comment by deYangar** [comment]
> 更了

请问像这个阿贝多更新了，但是一直用缓存的老图怎么办emmm

**Comment by SilveryStar** [comment]
啊，缓存是每周三定时清，你也可以手动把 /data/image 清空
下个版本再把这个管理命令补上吧XD

**Comment by deYangar** [comment]
> 啊，缓存是每周三定时清，你也可以手动把 /data/image 清空 下个版本再把这个管理命令补上吧XD

好的=-=
