### ISSUE TITLE
登录bot会挤掉当前的账号

### ISSUE THREAD

**Issue by MaoSource** [SilveryStar/Adachi-BOT#127]
有没有其他的登录方式，比如iPad登录什么的

**Comment by Annabel0530** [comment]
platform设置

**Comment by MaoSource** [comment]
> 平台设置

要怎么搞？

**Comment by Annabel0530** [comment]
https://docs.adachi.top/config/#platform
配置文件有写 可以看看

**Comment by MaoSource** [comment]
> https://docs.adachi.top/config/#platform 配置文件有写 可以看看

好的谢谢

**Comment by MaoSource** [comment]
> https://docs.adachi.top/config/#platform 配置文件有写 可以看看

在代码里面可以改么，我只想改这一个配置，给他写死在代码里

**Comment by SilveryStar** [comment]
为什么要写死在代码里，配置文件存在的目的不就是让你不用改代码吗…… 而且你改了代码可能就不能 git pull 更新了

**Comment by MaoSource** [comment]
> 为什么要写死在代码里，配置文件存在的目的不就是让你不用改代码吗…… 而且你改了代码可能就不能 git pull 更新了

是的这个我知道，就是我现在自己写了bot但是配置文件他识别不了，感觉只能写代码里面了

**Comment by SilveryStar** [comment]
没懂你什么意思……这个问题你应该去看 oicq 的文档

**Comment by MaoSource** [comment]
> 没懂你什么意思……这个问题你应该去看 oicq 的文档

是啊就是看半天oicq的文档没找到解决的办法，不应该在项目的目录下创建个config.js就能自动识别么？

**Comment by SilveryStar** [comment]
为什么，这又不是vue……

文档自己看 https://takayama-lily.github.io/oicq/modules.html#createClient
