### ISSUE TITLE
windows部署说明中有个连接地址错误

### ISSUE THREAD

**Issue by cao-zy** [SilveryStar/Adachi-BOT#129]
https://docs.adachi.top/deploy/windows.html#%E9%85%8D%E7%BD%AE
对于 cookies ，这是用来得到米游社数据的东西，每个米游社账号都是独一无二的，**这里** (opens new window)会告诉你如何获得它。

“这里”的连接为
http://localhost:8080/faq/#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%BE%97%E7%B1%B3%E6%B8%B8%E7%A4%BE-cookies

可更改为
https://docs.adachi.top/faq/#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%BE%97%E7%B1%B3%E6%B8%B8%E7%A4%BE-cookies
（小问题，看到了就提出来，希望大佬看到不要烦）

**Comment by SilveryStar** [comment]
修了 ~~其实有三个~~
