### ISSUE TITLE
运行中有几个功能有小问题想请教下

### ISSUE THREAD

**Issue by isad-name** [SilveryStar/Adachi-BOT#131]
问题有点多，希望大佬不要嫌烦 ，~~我已经很努力的看了好几遍说明和问题反馈了~~
1.今日素材（today）敲这个命令只会提示：
您还没有订阅过素材或 BOT 当日数据未更新，请先订阅素材并在早晨六点后再次尝试
我提前一天使用sub订阅了素材，早上了六点也自动推送了今天的素材图片，但敲today还是会提示这个

2.note功能会提示多次
![image](https://user-images.githubusercontent.com/66293690/144804097-5f91bef6-c3fb-4810-98f9-291b40dc8fc4.png)
不知道是不是我设置过树脂提醒量，如果是这个原因的话在哪可以看到或配置解决这种冲突提醒的问题
日志：
[14:53:19.240] [iPad:xxx] [INFO] - send to: [Private: 047 / message_id: QmABTwAADY/p3bbqYa2zXgE=]
[14:53:19.319] [iPad:xxx] [INFO] - send to: [Private: 047 / message_id: QmABTwAADZCRx+QZYa2zXgE=]

3.游戏查询uid和米游社查询mys都会返回
米游社接口报错: Please login
bind游戏uid，使用ps并确认cookie之后，便签查询功能已可用，但指令uid和mys都会提示上面的login（我未配置公用cookie）
我理解开启私人服务之后会优先使用私人的cookie去进行查询，不知道是我哪配置有问题，char也一样，估计是所有涉及到米游社查询的可能都存在问题

**Comment by SilveryStar** [comment]
~~有的不知道是不是 bug，因为我也很久没用过了~~
1. `silvery-star.today` 这个指令只负责个人的材料订阅，订阅群聊是不会返回内容的
2. 私人服务订阅情况不是很清楚，同时发生了很多条的话试着重启一下吧，还出问题再来反馈
3. 说实话不太清楚原因，如果 `silvery-star.now-note` 能用的话另外两个应该也能用，我先把我部署的版本改成 v2.2.2 看看能不能复现

**Comment by Annabel0530** [comment]
> ~有的不知道是不是 bug，因为我也很久没用过了~
> 
> 1. `silvery-star.today` 这个指令只负责个人的材料订阅，订阅群聊是不会返回内容的
> 2. 私人服务订阅情况不是很清楚，同时发生了很多条的话试着重启一下吧，还出问题再来反馈
> 3. 说实话不太清楚原因，如果 `silvery-star.now-note` 能用的话另外两个应该也能用，我先把我部署的版本改成 v2.2.2 看看能不能复现

1的话可以直接用一图览，发送关键词回复就行了  每天定时提醒不是很方便  毕竟大家清体力的时间不一样
https://bbs.mihoyo.com/ys/obc/content/1226/detail?bbs_presentation_style=no_header
https://bbs.mihoyo.com/ys/obc/content/1187/detail?bbs_presentation_style=no_header

**Comment by BennettChina** [comment]
关于today指令我的想法是订阅后的today指令去查询当天的订阅材料，这个返回内容可以直接使用推送内容的缓存。如果有了订阅有了更新再把缓存更新掉。

**Comment by isad-name** [comment]
> 

在我想法中差不多也是这个逻辑，可能和大佬设计的功能不太一样，我以为today指令是反馈一张图今日素材的图

**Comment by SilveryStar** [comment]
没事，下版本改（

**Comment by SilveryStar** [comment]
问题 2 可复现，排查原因中……

**Comment by SilveryStar** [comment]
查不出，重启服务器就又好了，而且看日志里没有你那样的连续的两条，貌似是遇上幽灵账号了（？
不知道你那边重新更新一下情况怎么样，目前确实没什么头绪

**Comment by isad-name** [comment]
> 查不出，重启服务器就又好了，而且看日志里没有你那样的连续的两条，貌似是遇上幽灵账号了（？ 不知道你那边重新更新一下情况怎么样，目前确实没什么头绪

上次重启之后目前暂未发现重复发送的问题复现，目前就uid和mys问题依旧，出现重复提示的那时候我根据提示试了一下手动设置树脂量的功能，有没有可能是这个地方引起的bug

**Comment by SilveryStar** [comment]
> 上次重启之后目前暂未发现重复发送的问题复现，目前就uid和mys问题依旧，出现重复提示的那时候我根据提示试了一下手动设置树脂量的功能，有没有可能是这个地方引起的bug

树脂量指令我用了也没问题…… uid和mys不能用反正是 cookie 的问题，要不你看看用这里 #134 的方法弄的 cookie 能不能用……

**Comment by isad-name** [comment]
> 

试了，不行，有没有可能是我我部署方式的问题，windows里下了docker，用docker那套命令跑的，套娃套多了？
不知道哪的问题我windows直接跑的话oicq程序跑不起来，docker里就可以
（跑不起来是日志刚开始能提示
Package Version: oicq@1.21.2 (Released on 2021/10/10)
View Changelogs：https://github.com/takayama-lily/oicq/releases
但是没有后面的连接服务器啥的，然后用docker-compose up -d这个命令在docker里跑就没啥问题）

**Comment by SilveryStar** [comment]
> 试了，不行，有没有可能是我我部署方式的问题，windows里下了docker，用docker那套命令跑的，套娃套多了？ 不知道哪的问题我windows直接跑的话oicq程序跑不起来，docker里就可以 （跑不起来是日志刚开始能提示 Package Version: oicq@1.21.2 (Released on 2021/10/10) View Changelogs：https://github.com/takayama-lily/oicq/releases 但是没有后面的连接服务器啥的，然后用docker-compose up -d这个命令在docker里跑就没啥问题）

啊这，那也是挺神奇的，本机还是服务器啊，我开发环境也是 windows，`npm start` 应该是能跑没问题的……（不过 windows docker 确实没试过），这个情况确实不清楚（捂脸
服务器的话有能力还是 linux 最方便

**Comment by isad-name** [comment]
> 

找了个笔记本新做的win10ltsc2021 linux实在是头疼，远程啥的还都是个问题，b站教程那个时候版本在win7下作的，没出现oicq的问题，那个版本就是alm黄历会直接报错崩溃，我以为系统或者node版本有问题就重做了win10试的

**Comment by SilveryStar** [comment]
> 找了个笔记本新做的win10ltsc2021 linux实在是头疼，远程啥的还都是个问题，b站教程那个时候版本在win7下作的，没出现oicq的问题，那个版本就是alm黄历会直接报错崩溃，我以为系统或者node版本有问题就重做了win10试的

你看眼 afd 吧（

**Comment by isad-name** [comment]
又测了一下，是我自己的问题，cookies.yml里我没改东西的问题，我随便填上两条就好使了，问题是配了私人服务mys应该不回去抓公用cookie啊，这地方是不是判断还是有点逻辑问题？或者是程序把默认填上的- cookieA给当成cookie用了

**Comment by SilveryStar** [comment]
> 又测了一下，是我自己的问题，cookies.yml里我没改东西的问题，我随便填上两条就好使了，问题是配了私人服务mys应该不回去抓公用cookie啊，这地方是不是判断还是有点逻辑问题？或者是程序把默认填上的- cookieA给当成cookie用了

今天刚修 f6fe1d66582a82d7c75be82cb6938af4c498ae27

**Comment by isad-name** [comment]
那正好晚上停下来pull了一下然后一起改了几个设置，顺带又发现个签到问题。
[2021-12-11T00:35:41.543] [ERROR] [iPad:229] - 服务器繁忙
[2021-12-11T00:35:41.544] [MARK] [iPad:229] - 5秒后重新连接。
[2021-12-11T00:35:41.555] [MARK] [iPad:229] - 157.255.13.76:8080 closed
[2021-12-11T00:35:41.559] [INFO] [iPad:229] - 用户 390 的米游社签到数据查询成功
[2021-12-11T00:35:41.568] [INFO] [iPad:229] - 用户 488 的米游社签到数据查询成功
[2021-12-11T00:35:41.579] [INFO] [iPad:229] - 用户 488 的实时便笺数据查询成功
[2021-12-11T00:35:41.600] [INFO] [iPad:29] - 用户 390 的实时便笺数据查询成功
[2021-12-11T00:35:41.606] [INFO] [iPad:29] - 用户 432 的米游社签到数据查询成功
[2021-12-11T00:35:41.632] [INFO] [iPad:29] - 用户 432 的实时便笺数据查询成功
[2021-12-11T00:35:41.753] [INFO] [iPad:9] - 用户 872 今日米游社签到成功
[2021-12-11T00:35:41.755] [ERROR] [iPad:29] - Invoke failed, because -> client is not online
[2021-12-11T00:35:41.780] [INFO] [iPad:29] - 用户 044 今日米游社签到成功
[2021-12-11T00:35:41.781] [ERROR] [iPad:229] - Invoke failed, because -> client is not online
[2021-12-11T00:35:41.844] [INFO] [iPad:9] - 用户 636 今日米游社签到成功
[2021-12-11T00:35:41.845] [ERROR] [iPad:229] - Invoke failed, because -> client is not online
[2021-12-11T00:35:41.861] [INFO] [iPad:29] - 用户 488 今日米游社签到成功
[2021-12-11T00:35:41.862] [ERROR] [iPad:9] - Invoke failed, because -> client is not online
[2021-12-11T00:35:41.876] [INFO] [iPad:29] - 用户 390 今日米游社签到成功
[2021-12-11T00:35:41.877] [ERROR] [iPad:229] - Invoke failed, because -> client is not online
[2021-12-11T00:35:41.895] [INFO] [iPad:29] - 用户 432 今日米游社签到成功
[2021-12-11T00:35:41.895] [ERROR] [iPad:29] - Invoke failed, because -> client is not online
不知道是不是我这网的问题，程序初始化之后总会出现好几次q登不上的问题，刚才启动程序应该是触发启动时检查米游社签到情况了，然后由于q还没登上，签到成功的信息其实是没发出去的，这块有没有稍作修改的可能比如启动一两分钟后开始执行查询及提醒。

还有之前说的today返回空白图片的问题今天还有，这种today刷新要不要考虑跟游戏时间同步
![image](https://user-images.githubusercontent.com/66293690/145617083-4578e13a-dbb8-40aa-9fd7-87ecc3b83971.png)

**Comment by isad-name** [comment]
> 那正好晚上停下来pull了一下然后一起改了几个设置，顺带又发现个签到问题。 [2021-12-11T00:35:41.543] [ERROR] [iPad:229] - 服务器繁忙 [2021-12-11T00:35:41.544] [MARK] [iPad:229] - 5秒后重新连接。 [2021-12-11T00:35:41.555] [MARK] [iPad:229] - 157.255.13.76:8080 closed [2021-12-11T00:35:41.559] [INFO] [iPad:229] - 用户 390 的米游社签到数据查询成功 [2021-12-11T00:35:41.568] [INFO] [iPad:229] - 用户 488 的米游社签到数据查询成功 [2021-12-11T00:35:41.579] [INFO] [iPad:229] - 用户 488 的实时便笺数据查询成功 [2021-12-11T00:35:41.600] [INFO] [iPad:29] - 用户 390 的实时便笺数据查询成功 [2021-12-11T00:35:41.606] [INFO] [iPad:29] - 用户 432 的米游社签到数据查询成功 [2021-12-11T00:35:41.632] [INFO] [iPad:29] - 用户 432 的实时便笺数据查询成功 [2021-12-11T00:35:41.753] [INFO] [iPad:9] - 用户 872 今日米游社签到成功 [2021-12-11T00:35:41.755] [ERROR] [iPad:29] - Invoke failed, because -> client is not online [2021-12-11T00:35:41.780] [INFO] [iPad:29] - 用户 044 今日米游社签到成功 [2021-12-11T00:35:41.781] [ERROR] [iPad:229] - Invoke failed, because -> client is not online [2021-12-11T00:35:41.844] [INFO] [iPad:9] - 用户 636 今日米游社签到成功 [2021-12-11T00:35:41.845] [ERROR] [iPad:229] - Invoke failed, because -> client is not online [2021-12-11T00:35:41.861] [INFO] [iPad:29] - 用户 488 今日米游社签到成功 [2021-12-11T00:35:41.862] [ERROR] [iPad:9] - Invoke failed, because -> client is not online [2021-12-11T00:35:41.876] [INFO] [iPad:29] - 用户 390 今日米游社签到成功 [2021-12-11T00:35:41.877] [ERROR] [iPad:229] - Invoke failed, because -> client is not online [2021-12-11T00:35:41.895] [INFO] [iPad:29] - 用户 432 今日米游社签到成功 [2021-12-11T00:35:41.895] [ERROR] [iPad:29] - Invoke failed, because -> client is not online 不知道是不是我这网的问题，程序初始化之后总会出现好几次q登不上的问题，刚才启动程序应该是触发启动时检查米游社签到情况了，然后由于q还没登上，签到成功的信息其实是没发出去的，这块有没有稍作修改的可能比如启动一两分钟后开始执行查询及提醒。
> 
> 还有之前说的today返回空白图片的问题今天还有，这种today刷新要不要考虑跟游戏时间同步 ![image](https://user-images.githubusercontent.com/66293690/145617083-4578e13a-dbb8-40aa-9fd7-87ecc3b83971.png)

抱歉打扰了（手动滑稽）~~pull的时候翻车了~~，整个重新搞了一遍现在today没问题了
