### ISSUE TITLE
查询深渊的图片加载不出来

### ISSUE THREAD

**Issue by beiju97** [SilveryStar/Adachi-BOT#132]
### 系统版本

Ubuntu 20.04.3 LTS

### Node.js 版本

v16.13.1

### 应用版本

"version": "2.2.2",

### 启动方式

Docker

### 复述操作

查询深渊 bot 转发聊天记录的图片加载不出来，换过账号设备和网络测试过，也都加载不出来。
不知道是不是只有2G内存的关系，不知道大家有没有遇到这种问题，还麻烦大佬解答下。
![BGX6G8C1H3L@7J{P21X6SY6](https://user-images.githubusercontent.com/76851063/144898096-dde4a3aa-969c-4775-8b11-2d9c3ee592b8.png)
![%U`IQ){{}GUN86R@)CNH9FG](https://user-images.githubusercontent.com/76851063/144897981-41fd12f4-0116-4238-bbb4-f73cfbf5c85d.png)
![EF11E7DA92F47047AA3682B02D8890AA](https://user-images.githubusercontent.com/76851063/144898369-324bd265-4e8f-4397-8fa4-c4b86be1b8f4.png)

**Comment by SilveryStar** [comment]
已知问题，私聊经常看不到，以后会改
