### ISSUE TITLE
关于米游社 cookie 的部分事项

### ISSUE THREAD

**Issue by SilveryStar** [SilveryStar/Adachi-BOT#134]
本项目将在 v2.2.3 版本的更新中为私人服务添加米游社原神签到功能，由于[文档](https://docs.adachi.top/faq/#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%BE%97%E7%B1%B3%E6%B8%B8%E7%A4%BE-cookies)中的方式获取的 cookie 无法用于签到 ~~，没错就是这东西耽误了两天开发进度，还搞得我血压狂飙~~，用户可以在版本更新前修改私人服务中绑定的 cookie，方法如下:
1. 打开浏览器的 **无痕浏览模式** 或 **隐身模式**
2. 进入 `http://bbs.mihoyo.com/ys/` 并登录账号
3. 点击 F12 ，选中 Console 或控制台，输入 `document.cookie` ，回车即可获取

以上步骤参考 [此项目](https://github.com/Womsxd/AutoMihoyoBBS#%E8%8E%B7%E5%8F%96%E7%B1%B3%E6%B8%B8%E7%A4%BEcookie)
同时也感谢 @wickedll 为本项目制作相关插件 ~~只是时机太不巧了~~

**Comment by wickedll** [comment]
哈哈哈  我随便写写  还得是官方

**Comment by wickedll** [comment]
> 本项目将在 v2.2.3 版本的更新中为私人服务添加米游社原神签到功能，由于[文档](https://docs.adachi.top/faq/#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%BE%97%E7%B1%B3%E6%B8%B8%E7%A4%BE-cookies)中的方式获取的 cookie 无法用于签到 ~，没错就是这东西耽误了两天开发进度，还搞得我血压狂飙~，用户可以在版本更新前修改私人服务中绑定的 cookie，方法如下:
> 
> 1. 打开浏览器的 **无痕浏览模式** 或 **隐身模式**
> 2. 进入 `http://bbs.mihoyo.com/ys/` 并登录账号
> 3. 点击 F12 ，选中 Console 或控制台，输入 `document.cookie` ，回车即可获取
> 
> 以上步骤参考 [此项目](https://github.com/Womsxd/AutoMihoyoBBS#%E8%8E%B7%E5%8F%96%E7%B1%B3%E6%B8%B8%E7%A4%BEcookie) 同时也感谢 @wickedll 为本项目制作相关插件 ~只是时机太不巧了~

我也刚加私人服务  不过没有加定时的功能

**Comment by VsentCN** [comment]
我现在找不到Adachi-BOT 的插件合集的入口，现在是用的以前的网址访问，这个没有放在官方文档里吗

**Comment by wickedll** [comment]
> 我现在找不到Adachi-BOT 的插件合集的入口，现在是用的以前的网址访问，这个没有放在官方文档里吗

https://github.com/SilveryStar/Adachi-Plugin

**Comment by SilveryStar** [comment]
> 我现在找不到Adachi-BOT 的插件合集的入口，现在是用的以前的网址访问，这个没有放在官方文档里吗

之前忘记放 README 了，刚加上（x

**Comment by VsentCN** [comment]
开启无痕模式获取的cookies可以用在cookies.yml配置文件中吗，还是说只是私人服务使用。

**Comment by SilveryStar** [comment]
> 开启无痕模式获取的cookies可以用在cookies.yml配置文件中吗，还是说只是私人服务使用。

 看起来是通用的

**Comment by VsentCN** [comment]
我看也只是多了MHYUUID和mi18nLang，那是不是文档的方法删去这两项就可以用了？

**Comment by wickedll** [comment]
我直接从网络请求中复制出来的cookie也是能用的

**Comment by SilveryStar** [comment]
> 我看也只是多了MHYUUID和mi18nLang，那是不是文档的方法删去这两项就可以用了？

关键字段应该是 `cookie_token` ，之前那种方法的没有

**Comment by VsentCN** [comment]
> > 我看也只是多了MHYUUID和mi18nLang，那是不是文档的方法删去这两项就可以用了？
> 
> 关键字段应该是 `cookie_token` ，之前那种方法的没有

我用谷歌浏览器没开无痕获取的cookies也是有`cookie_token`字段，对比无痕只是多了两项

**Comment by SilveryStar** [comment]
> 我用谷歌浏览器没开无痕获取的cookies也是有`cookie_token`字段，对比无痕只是多了两项

这就不是很清楚了……

**Comment by AzusaYukina** [comment]
> > 我用谷歌浏览器没开无痕获取的cookies也是有`cookie_token`字段，对比无痕只是多了两项
> 
> 这就不是很清楚了……

只要是刚登陆就获取 token 都可以拿到 `cookie_token` 字段，如果之前登陆过了现在直接打开拿 token 是没有这个字段的
倒不是无痕浏览的问题

**Comment by VsentCN** [comment]
米游社签到输入指令后会签到一次还是之后会定时签到

**Comment by SilveryStar** [comment]
> 米游社签到输入指令后会签到一次还是之后会定时签到

目前是只有以后定时。这部分之后会优化成使用 `signin` 后尝试签到一次，并且以后定时签到

**Comment by VsentCN** [comment]
> > 米游社签到输入指令后会签到一次还是之后会定时签到
> 
> 目前是只有以后定时。这部分之后会优化成使用 `signin` 后尝试签到一次，并且以后定时签到

目前定时是几点，考虑到机器人有可能会出现掉线等情况，错过定时签到的时间，以后会不会出一个功能就可以更改签到定时，以及指令可以把所有使用私人服务的账号签到。

**Comment by SilveryStar** [comment]
> 目前定时是几点，考虑到机器人有可能会出现掉线等情况，错过定时签到的时间，以后会不会出一个功能就可以更改签到定时，以及指令可以把所有使用私人服务的账号签到。

八点，更改定时不会有（毕竟你要是机器人掉线了改了定时也没用），会有启动时尝试签到所有服务的账号
