### ISSUE TITLE
`mys` 及 `uid` 在特定情况下查询结果不全

### ISSUE THREAD

**Issue by AzusaYukina** [SilveryStar/Adachi-BOT#135]
### 系统版本

Windows 10 Pro (19043.1348)

### Node.js 版本

12.22.7

### 应用版本

2.2.2

### 复述操作

更新至 2.2.2 版本后，在测试查询账号信息功能时，使用公用 token 获取自己账户信息（可用且正常），随后自己尝试获取自己的账号信息（此时使用对应账号的 token），仅有好感前 8 可以查询。
推测是由于账号信息刷新机制所致。

### 配置文件

```YAML
未修改
```

### 错误报告

```Text
无有关日志
```

**Comment by SilveryStar** [comment]
可以给一点更详细的描述吗，这说的我有点晕：比如 a 的 cookie 查谁的信息之类的，然后顺便发一下图

**Comment by AzusaYukina** [comment]
群友1：/uid [我的 uid]
bot：返回了图片，有我的好感度前 8 的角色数据
随即，我：/mys
bot：返回了图片，仍然只有我的好感度前 8 的角色数据，没有其他的

**Comment by AzusaYukina** [comment]
现在版本不是说，开启了私人服务之后可以查到自己的全部角色数据吗
但是在上述情景下，似乎数据不会刷新（

**Comment by SilveryStar** [comment]
> 现在版本不是说，开启了私人服务之后可以查到自己的全部角色数据吗 但是在上述情景下，似乎数据不会刷新（

嗯，因为数据库里用的是相同的字段，所有 uid 指令先用就把这里占掉了，后面用 mys 程序以为这里已经有数据就会跳过，bugfix1 来修（

**Comment by AzusaYukina** [comment]
辛苦啦
