### ISSUE TITLE
循环依赖错误，nodejs版本过高引起

### ISSUE THREAD

**Issue by KimigaiiWuyi** [SilveryStar/Adachi-BOT#14]
报错信息
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: app.ts
(node:21564) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21564) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency

疑似使用nodejs v14+版本引起，望解决

**Comment by SilveryStar** [comment]
排查了一下，在开发环境（windows10 pro 20H2, node.js v14.17.1）使用 `npm start` 可以正常运行，`npm run serve` 可以复现，问题出在 `forever` 上，参考 [[forever issue $1077]](https://github.com/foreversd/forever/issues/1077) ，目前好像没有比较好的解决方法，只能降低 node 版本了

**Comment by SilveryStar** [comment]
后续会给出 docker 版本的，现在只能这样了(sigh

**Comment by MiniGrayGay** [comment]
![image](https://user-images.githubusercontent.com/64829926/123570271-6e76b000-d7fa-11eb-9a24-981afdd3667d.png)

好像在node12版本也会提示这个错误

**Comment by misaka10843** [comment]
实测centos7.6
node.js 版本12.22.1也有这种错误，但是也无法使用docker启动
下面是npm运行的错误
```bash
[root@VM-12-11-centos Adachi-BOT]# node -v
v12.22.1
[root@VM-12-11-centos Adachi-BOT]# npm run serve

> adachi-bot@2.0.3 serve /www/wwwroot/Adachi-BOT
> forever start -v -c ts-node app.ts

warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: app.ts
[root@VM-12-11-centos Adachi-BOT]# 
```

**Comment by misaka10843** [comment]
centos7.6
node.js ver.11.0.0也出现错误
```bash

  ο node/11.0.0
    node/12.0.0

Use up/down arrow keys to select a version, return key to install, d to delete, q to quit   installe
d : v11.0.0 (with npm 6.4.1)
[root@VM-12-11-centos Adachi-BOT]# npm run serve

> adachi-bot@2.0.3 serve /www/wwwroot/Adachi-BOT
> forever start -v -c ts-node app.ts

warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: app.ts
```

**Comment by JohnZanZheng** [comment]
有没有碰到过 centOS7.8下 把启动脚本写给 systemd，用systemctl start 某service这样去起。 然后显示进程有了， 但是却打不开页面。但是如果不用systemctl注册服务启动，直接手动sh 启动脚本，就能够访问页面这种奇葩的情况。 是forever 3.0.4跟node 16

**Comment by SilveryStar** [comment]
> 有没有碰到过 centOS7.8下 把启动脚本写给 systemd，用systemctl start 某service这样去起。 然后显示进程有了， 但是却打不开页面。但是如果不用systemctl注册服务启动，直接手动sh 启动脚本，就能够访问页面这种奇葩的情况。 是forever 3.0.4跟node 16

好像没
