### ISSUE TITLE
两个小问题

### ISSUE THREAD

**Issue by tian564159391** [SilveryStar/Adachi-BOT#144]
### 系统版本

windows

### Node.js 版本

14.17.6

### 应用版本

2.2.4

### 复述操作

1.私人服务中米游社签到提示 米游社接口报错: 尚未登录
按照插件作者的回复，重新获取cookie后依然会有这个问题。我在他那边也留言了=m=，看看哪边有办法...

2.webConsole,未修改端口地址，不论是通过其他电脑访问ip，或者是在云服务器上用localhost进行本地访问都是白屏。
![image](https://user-images.githubusercontent.com/37993579/145951725-fb24dc3e-7ed3-4961-981b-b0b1b66d4b22.png)
![image](https://user-images.githubusercontent.com/37993579/145951736-b77d9885-eb65-4d75-9214-556737c5121d.png)

**Comment by SilveryStar** [comment]
你倒是给错误报告和配置啊，你这样我只能帮你算一卦

**Comment by tian564159391** [comment]
webConsole:
  enable: true
  consolePort: 80
  tcpLoggerPort: 54921
  jwtSecret: "SBqusiba5408"

额，并没有报错的报告=-= 配置就是这样的，按照文档里的说明输入云服务器ip 网页是白屏 更换浏览器也不行...也不知道问题在哪...所以不行就算了...----大吉----

**Comment by SilveryStar** [comment]
那就把浏览器 f12 的控制台截图出来

**Comment by tian564159391** [comment]
> 那就把浏览器 f12 的控制台截图出来

![image](https://user-images.githubusercontent.com/37993579/145953536-56cfa4be-823e-410f-84f9-81f5a48c6bb1.png)

**Comment by tian564159391** [comment]
> 那就把浏览器 f12 的控制台截图出来
这个是在云服务器用localhost的控制台
![image](https://user-images.githubusercontent.com/37993579/145953812-25ced8e2-f792-4b72-aed4-8c3ae3437dca.png)

**Comment by SilveryStar** [comment]
单纯的网络问题

**Comment by tian564159391** [comment]
> 单纯的网络问题

0.0好吧我研究一下

**Comment by SilveryStar** [comment]
签到见 #134，必须包含 cookie_token 才能用
