### ISSUE TITLE
`char` 指令返回出错，仅能返回固定角色

### ISSUE THREAD

**Issue by AzusaYukina** [SilveryStar/Adachi-BOT#148]
### 系统版本

Windows 10 Pro (19043.1348)

### Node.js 版本

12.22.7

### 应用版本

2.2.5

### 复述操作

拉取代码更新后，使用 `char` 查询角色详情时，无论查询什么角色固定返回好感度最高的角色。
（大概是 `mys` 图片里面的第一个角色）
另：此前的版本（`>2.2.3` 但是不记得是哪个了）同样有该问题。

### 配置文件

```YAML
无修改
```

### 错误报告

```Text
无错误报告
```

**Comment by SilveryStar** [comment]
~~这也火星太久了~~
米游社接口问题，之后会改（加个频道呗

**Comment by AzusaYukina** [comment]
~~原来我火星了那没事了~~主要是没人用，今天刚用才发现
频道的话，鹅不给我内测，进不去（安详）

**Comment by SilveryStar** [comment]
> 频道的话，鹅不给我内测，进不去（安详）

进群用通行证拉就自动开内测资格了
