### ISSUE TITLE
【公告】云服务器部署出现的功能错误

### ISSUE THREAD

**Issue by SilveryStar** [SilveryStar/Adachi-BOT#154]
2021年12月24日 11:30 左右，米游社数据接口进行了更新且设置了防火墙，目前疑似来自内陆的服务商（阿里云等）的请求都会被禁止（ https://github.com/Arondight/Adachi-BOT/issues/522 ），以下功能都会失效：
* `char` - 角色信息
* `uid` - 游戏查询
* `private` - 私人服务
  - `note` - 实时便笺
  - `mys` - 游戏查询
  - `signin` 米游社签到
  - `abyss` 深渊查询

以上，是否存在解决方法暂时未知。
目前接口格式已经更新，本机部署可以正常使用，非大陆地区或境外服务器（可能）可以正常使用。

**Comment by King-Nameless** [comment]
这也太惨了吧，最重要的几个功能全寄了啊，本机部署不太现实啊，哪有挂个机器人一直开着电脑的_(:зゝ∠)_

**Comment by 1055169799** [comment]
目前我能想出的方法是用CCProxy，在插件里把机器人的数据通过映射端口到个人/公司的电脑上，转发给米游社，然后得到结果再传回去。要求就是个人电脑不能关机（公司电脑不关机应该还好），但经过这步转发，出消息的速度上可能会慢一些。

**Comment by VsentCN** [comment]
> 目前我能想出的方法是用CCProxy，在插件里把机器人的数据通过映射端口到个人/公司的电脑上，转发给米游社，然后得到结果再传回去。要求就是个人电脑不能关机（公司电脑不关机应该还好），但经过这步转发，出消息的速度上可能会慢一些。

如果可以个人电脑一直开，那就可以把Bot放个人电脑上了。

**Comment by 1055169799** [comment]
> > 目前我能想出的方法是用CCProxy，在插件里把机器人的数据通过映射端口到个人/公司的电脑上，转发给米游社，然后得到结果再传回去。要求就是个人电脑不能关机（公司电脑不关机应该还好），但经过这步转发，出消息的速度上可能会慢一些。
> 
> 如果可以个人电脑一直开，那就可以把Bot放个人电脑上了。

挂本地电脑主要是资源占用，我的电脑经常跑渲染，一般都会把所有后台都关掉保证稳定。相对来说，开个端口映射功能要好一些。

**Comment by King-Nameless** [comment]
> 

这样的话还不如另搞个垃圾电脑，比如捡垃圾组一台，好像100左右就行，有旧的电脑配件还能更便宜，服务器费用都省了，性能还比那种菜鸡服务器强
