### ISSUE TITLE
机器人卡死问题

### ISSUE THREAD

**Issue by EightMonth** [SilveryStar/Adachi-BOT#159]
当输入指令 wish|w until时，机器人后面将无法响应其它任何指令

机器人master 可以使用wish|w 指令，但是无法在后面加入参数，加入参数后，将只返回统计数量，不返回卡片内容
![image](https://user-images.githubusercontent.com/23272421/147815783-530ae11f-9c30-467c-b85d-3939c5f6fa87.png)

**Comment by SilveryStar** [comment]
你的问题，可能是版本没更新上，完成重新部署不存在这种行为
