### ISSUE TITLE
[功能更新请求] 米游社页面user-base：增加渊下宫探索度

### ISSUE THREAD

**Issue by Mark9804** [SilveryStar/Adachi-BOT#161]
Arondight 那边[我已经适配完了](https://github.com/Arondight/Adachi-BOT/tree/master/src/views)，还没细调，而且数据结构不知道一不一样就不提pr了（主要是急着锄渊下宫.jpg）

我那边是这样的
![image](https://user-images.githubusercontent.com/9006264/148395828-6ff86853-4fdc-4459-a78c-df7e7ba9946a.png)

另外我在大佬的基础上把布局模型都改成了grid和flex，网页和元素高度全部改了自适应，扩展起来更灵活，Logo也懒得自己画了，从米游社那边抓下来区域logo给mask上去，虽然效果不够精细但是会减轻很多自己画图标的工作量，大佬要是喜欢的话可以直接拿走

![image](https://user-images.githubusercontent.com/9006264/148395029-cee3092a-75bd-4ea9-aabb-2781764685a6.png)

**Comment by SilveryStar** [comment]
谢邀，刚锄完地，晚上再看（x
