### ISSUE TITLE
查询深渊，私聊发送，图片裂开。群聊发送没问题

### ISSUE THREAD

**Issue by deYangar** [SilveryStar/Adachi-BOT#162]
### 系统版本

Windows 10 专业工作站版 1909

### Node.js 版本

v13.13.0

### 应用版本

2.2.7

### 启动方式

Forever

### 复述操作

如果一个人，之前成功查询过，有缓存，那他的图是正常的
如果一个人，新深渊打了后，没查询过，第一次查询，那图就是裂开的
这是查过的
![QQ截图20220108205155](https://user-images.githubusercontent.com/70438628/148644854-284ef926-482b-4c18-add0-91874c941f8a.jpg)
这是没查过的
![QQ图片20220108205046](https://user-images.githubusercontent.com/70438628/148644871-738d01d4-b3be-49cc-98cb-0de308216ce0.png)

### 配置文件

```YAML
src/plugins/genshin/utils/api.ts 文件没动过，是2.2.7最新版
```

### 错误报告

```Text
无错误报告
```

**Comment by deYangar** [comment]
图一的聊天记录截图有歧义，那个人的上期深渊是查询过的

**Comment by deYangar** [comment]
不对，找多了几个群友试，更奇怪了
私发的图是裂的，群发的图是好的
这是同一个号，左边是群聊，右边是私聊
![QQ截图20220108205708](https://user-images.githubusercontent.com/70438628/148645046-70d32325-a0ff-48a5-9ceb-1517d775ed79.jpg)

**Comment by Annabel0530** [comment]
這個老毛病的 其他issues提過

**Comment by deYangar** [comment]
但是控制台显示的都是发送成功，没报错的

**Comment by deYangar** [comment]
> 這個老毛病的 其他issues提過

啊这 好的

**Comment by SilveryStar** [comment]
这属于库的行为问题

**Comment by deYangar** [comment]
> 这属于库的行为问题

好的👌
