### ISSUE TITLE
「祈愿抽卡」功能异常

### ISSUE THREAD

**Issue by Accelerator1213** [SilveryStar/Adachi-BOT#164]
### 系统版本

centos_8_0_x64

### Node.js 版本

13.13.0

### 应用版本

2.2.7

### 启动方式

Docker

### 复述操作

抽卡过程中可能会因为未获取到卡池保底信息导致十连一直不出紫，如果此时使用#w+次数会返回空白抽卡结果，如果使用#w until，则会引发CPU拉满（可能是bot因为无法获得五星物品而持续模拟抽卡？）。

![918VD1M77%Y OD J8_6E)V](https://user-images.githubusercontent.com/82789349/149052178-1913367f-86bf-44f3-9268-219d65117c06.png)

![XB%_3UJF51HZ%7R(3IT7Q_7](https://user-images.githubusercontent.com/82789349/149052226-d83440c8-f06f-44bf-aa90-95e0d38e9f80.png)

### 配置文件

```YAML
未修改
```

### 错误报告

```Text
未发生错误报告（至少看不到控制台报错。。）
```

**Comment by SilveryStar** [comment]
我这又是无法复现…… 没办法进行错误定位，可能是数据库或者获取卡池信息时的网络问题，挺奇怪的
目前我先给抽卡指令加个限制和消息返回吧，不太好解决
