### ISSUE TITLE
绑定多个账号后，`char`指令无法指定具体账号

### ISSUE THREAD

**Issue by AzusaYukina** [SilveryStar/Adachi-BOT#179]
### 系统版本

Windows 10 Pro (19043.1348)

### Node.js 版本

12.22.7

### 应用版本

2.2.9

### 复述操作

绑定多个账号后，使用 `char 2 甘雨` 提示角色名称错误
![f9499c940851f141ac2822a90a9ed331](https://user-images.githubusercontent.com/53286112/154847501-338c78e1-f99c-4d20-85a4-7b1c454e69cf.png)

### 配置文件

```YAML
无
```

### 错误报告

```Text
无
```

**Comment by SilveryStar** [comment]
来点补充信息，这个QQ号绑定了哪些米游社账号，分别有什么角色
