### ISSUE TITLE
WebConsole日志28日无法展示

### ISSUE THREAD

**Issue by BennettChina** [SilveryStar/Adachi-BOT#184]
### 系统版本

Centos8

### Node.js 版本

v17.2.0

### 应用版本

2.2.9-bugfix4

### 启动方式

Docker

### 复述操作

<img width="575" alt="image" src="https://user-images.githubusercontent.com/48208644/155963462-57526720-1433-4e48-874f-ebf6626e8adf.png">

<img width="529" alt="image" src="https://user-images.githubusercontent.com/48208644/155963569-cc6519e9-a1d3-490c-ae5f-29529b95d2d0.png">

**Comment by BennettChina** [comment]
今天又看了下，是当天的日志找不到，并且只保留了昨天和今天的日志，27日的日志已被删除。日志是不是可以保留时间长一点比如30天？以及当天日志看不到也需要修复下。

**Comment by SilveryStar** [comment]
emmmm, 日志是没有自动清理机制的，可能是你那边服务器设置之类的问题……？

**Comment by BennettChina** [comment]
日志清理暂时还找不到原因，服务器也没搞定时任务清理日志，奇怪🤔。当天日志看不到原因倒是找到了，是我把webConsole域名升级到https导致websocket链接失败导致的，我重新配置了nginx以及改了代码使用wss协议倒是解决了。日志清理问题再观察两天。
