### ISSUE TITLE
windows部署怎么实现后台运行？

### ISSUE THREAD

**Issue by linjie5492** [SilveryStar/Adachi-BOT#187]
### 系统版本

windows server 2012

### Node.js 版本

node 16

### 应用版本

默认的

### 复述操作

问下这个项目在windows中，npm start之后，怎么才能在后台运行，如果是node项目，可以使用pm2做到后台运行，但是这个我不太会弄怎么弄到后台？

**Comment by SilveryStar** [comment]
因为这个项目是 ts-node 运行未编译的 typescript，pm2 不能用，forever 在 Windows 上有问题
要么换 Linux 要么 docker
