### ISSUE TITLE
请问老API还维护吗

### ISSUE THREAD

**Issue by Arondight** [SilveryStar/Adachi-BOT#21]
最近看你更了2.0，1.0 的API 已经不支持新的人物和武器了，我自己试着迁移了下，没写过Node 比较费劲，请问你这还会维护1.0 的API 吗

**Comment by SilveryStar** [comment]
不会了，1.0的路径组织有点乱，方便的话还是换到新版本吧

**Comment by Arondight** [comment]
好的，目前overview 插件还有点问题，我自己试着解决一下，谢谢
