### ISSUE TITLE
请问bot启动后如何查看后台日志呢？机器人的使用说明指令是哪个？

### ISSUE THREAD

**Issue by Nigel-NI** [SilveryStar/Adachi-BOT#23]
运行docker-compose up -d后返回
`Starting redis ... done
Starting bot   ... done`
但是QQ输入help或#help后机器人无反应。我想看一下后台日志，但是不知道如何进入后台查看，想请教一下开发大大。
顺便想了解一下机器人在qq侧的调用指令，比如我想查询某武器的信息需要输入什么指令。第一次使用这个bot，很多内容不了解，还望见谅！

**Comment by SilveryStar** [comment]
（docker的日志目录忘记配置了，回头加上）
使用配置的 `setting.yml.header`+help （例如 `#help`）查看命令

**Comment by SilveryStar** [comment]
[已更新](https://github.com/SilveryStar/Adachi-BOT/commit/f1c5b4d020baf5d180ed8703506fe65f9c91defb)
