### ISSUE TITLE
bot启动后发送help等指令无响应

### ISSUE THREAD

**Issue by Nigel-NI** [SilveryStar/Adachi-BOT#24]
以下为输出日志（敏感信息已隐藏），服务端已经收到了来自QQ的help指令，但是没有做出回复：
> {"log":"\u001b[90m[2021-07-13T14:27:22.250] [MARK] [Android:000] - \u001b[39m----------\n","stream":"stdout","time":"2021-07-13T14:27:22.272061142Z"}
{"log":"\u001b[90m[2021-07-13T14:27:22.271] [MARK] [Android:000] - \u001b[39mPackage Version: oicq@1.17.3 (Released on 2021/6/6)\n","stream":"stdout","time":"2021-07-13T14:27:22.272104828Z"}
{"log":"\u001b[90m[2021-07-13T14:27:22.271] [MARK] [Android:000] - \u001b[39mView Changelogs：https://github.com/takayama-lily/oicq/releases\n","stream":"stdout","time":"2021-07-13T14:27:22.272112685Z"}
{"log":"\u001b[90m[2021-07-13T14:27:22.271] [MARK] [Android:000] - \u001b[39m----------\n","stream":"stdout","time":"2021-07-13T14:27:22.272117347Z"}
{"log":"\u001b[90m[2021-07-13T14:27:22.275] [MARK] [Android:000] - \u001b[39m正在探索可用服务器...\n","stream":"stdout","time":"2021-07-13T14:27:22.275565504Z"}
{"log":"\u001b[32m[2021-07-13T14:27:23.624] [INFO] [Android:000] - \u001b[39m插件 @auth 已成功加载\n","stream":"stdout","time":"2021-07-13T14:27:23.62443587Z"}
{"log":"\u001b[32m[2021-07-13T14:27:24.309] [INFO] [Android:000] - \u001b[39m插件 @help 已成功加载\n","stream":"stdout","time":"2021-07-13T14:27:24.31009755Z"}
{"log":"\u001b[33m[2021-07-13T14:27:28.635] [WARN] [Android:000] - \u001b[39m探索服务器失败: timeout\n","stream":"stdout","time":"2021-07-13T14:27:28.636337812Z"}
{"log":"\u001b[90m[2021-07-13T14:27:28.635] [MARK] [Android:000] - \u001b[39mconnecting to msfwifi.3g.qq.com:8080\n","stream":"stdout","time":"2021-07-13T14:27:28.63685967Z"}
{"log":"\u001b[32m[2021-07-13T14:27:28.642] [INFO] [Android:000] - \u001b[39mRedis 数据库已连接\n","stream":"stdout","time":"2021-07-13T14:27:28.644345649Z"}
{"log":"\u001b[90m[2021-07-13T14:27:28.644] [MARK] [Android:000] - \u001b[39m203.205.255.220:8080 connected\n","stream":"stdout","time":"2021-07-13T14:27:28.644735271Z"}
{"log":"\u001b[36m[2021-07-13T14:27:28.819] [DEBUG] [Android:000] - \u001b[39m{\n","stream":"stdout","time":"2021-07-13T14:27:28.82336974Z"}
{"log":"  '114.221.144.89': 14000,\n","stream":"stdout","time":"2021-07-13T14:27:28.823405913Z"}
{"log":"  '14.215.138.110': 80,\n","stream":"stdout","time":"2021-07-13T14:27:28.823411724Z"}
{"log":"  '203.205.255.220': 8080\n","stream":"stdout","time":"2021-07-13T14:27:28.823415557Z"}
{"log":"}\n","stream":"stdout","time":"2021-07-13T14:27:28.823419382Z"}
{"log":"\u001b[90m[2021-07-13T14:27:28.921] [MARK] [Android:000] - \u001b[39mWelcome, YY ! 初始化资源...\n","stream":"stdout","time":"2021-07-13T14:27:28.922165079Z"}
{"log":"\u001b[90m[2021-07-13T14:27:29.098] [MARK] [Android:000] - \u001b[39m加载了3个好友，2个群。\n","stream":"stdout","time":"2021-07-13T14:27:29.098386121Z"}
{"log":"\u001b[90m[2021-07-13T14:27:29.102] [MARK] [Android:000] - \u001b[39m初始化完毕，开始处理消息。\n","stream":"stdout","time":"2021-07-13T14:27:29.103003612Z"}
{"log":"(node:17) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined\n","stream":"stderr","time":"2021-07-13T14:27:29.44770925Z"}
{"log":"    at new Cookies (/bot/src/plugins/genshin/module/cookies.ts:11:30)\n","stream":"stderr","time":"2021-07-13T14:27:29.4477405Z"}
{"log":"    at /bot/src/plugins/genshin/init.ts:137:12\n","stream":"stderr","time":"2021-07-13T14:27:29.447745926Z"}
{"log":"    at step (/bot/src/plugins/genshin/init.ts:44:23)\n","stream":"stderr","time":"2021-07-13T14:27:29.447750025Z"}
{"log":"    at Object.next (/bot/src/plugins/genshin/init.ts:25:53)\n","stream":"stderr","time":"2021-07-13T14:27:29.447769425Z"}
{"log":"    at fulfilled (/bot/src/plugins/genshin/init.ts:16:58)\n","stream":"stderr","time":"2021-07-13T14:27:29.447773529Z"}
{"log":"    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n","stream":"stderr","time":"2021-07-13T14:27:29.4477768Z"}
{"log":"(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)\n","stream":"stderr","time":"2021-07-13T14:27:29.447937277Z"}
{"log":"(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.\n","stream":"stderr","time":"2021-07-13T14:27:29.448085076Z"}
{"log":"\u001b[32m[2021-07-13T14:28:09.404] [INFO] [Android:000] - \u001b[39mrecv from: [Group: 讨论组(00), Member: XX(000)] help\n","stream":"stdout","time":"2021-07-13T14:28:09.41746551Z"}

setting.yml已设置headlers为空（""），以下为部分commands.yml内容：

```
 adachi.help:
  - help
adachi.detail:
  - detail
```

期待作者大大的回复，谢谢！

**Comment by SilveryStar** [comment]
以下摘自框架 `oicq` 内代码：
```
 * 关于探索服务器：
 * 由于tx服务器偶尔会抽风，若固定使用域名msfwifi.3g.qq.com连接，遇到抽风的IP会炸
 * 探索服务器每次获得3个理论最优IP，一小时内只进行一次探索，除非IP已经用完
 * 在连接后5分钟内若出现断线，则判断此IP抽风，将其排除
 * 5分钟之外的断线则正常重连
 * 同一线程中的所有客户端实例共用一个IP池
```
日志反馈 `探索服务器失败: timeout`，请检查网络状况并重启应用（或设备）

关于其他问题：
`cookies.yml` 格式有误
```yaml
# true
cookies:
  - xxxxxx

# false
cookies: xxxxxx
```

**Comment by Nigel-NI** [comment]
感谢回复。问题已解决
