### ISSUE TITLE
祈愿十连的实现有些问题

### ISSUE THREAD

**Issue by XingNian-www** [SilveryStar/Adachi-BOT#25]
测试中上千次抽取没有一次双黄
应该是抽卡保底的实现有点问题
更新,群友又抽了几百次,只有一次双黄emmm
然后瞬间请求过多会产生相同的结果
![image](https://user-images.githubusercontent.com/44593434/125500449-a9bfc5f6-3779-4072-8f6b-87b27664bd43.png)

**Comment by SilveryStar** [comment]
首先游戏对“双黄”没有任何保底机制

**Comment by SilveryStar** [comment]
然后关于重复，除非单个人在1秒内进行了超过三次抽卡，在服务器性能正常的情况下都不会有问题（刷屏的建议禁言了）

**Comment by XingNian-www** [comment]
> 首先游戏对“双黄”没有任何保底机制

就是概率上的双黄感觉太低了,我去找找数据

**Comment by XingNian-www** [comment]
> 首先游戏对“双黄”没有任何保底机制

看了看代码,都是用的平衡树的那个结论
难不成真的是我群友跟我运气太黑,上千次十连就一个双黄,惨啊
关闭了关闭了

**Comment by XingNian-www** [comment]
还有几个小问题
比如抽取圣遗物,选择秘境后只出一种圣遗物,这应该是bug吧
火本迫真降低血压~~建议在火本当做特性~~
或者干脆可以直接选择抽哪种圣遗物

然后是抽卡建议加一个当前未出金的抽数**~~直观的看到有多非~~**
