### ISSUE TITLE
Node.js v12具体什么版本

### ISSUE THREAD

**Issue by Annabel0530** [SilveryStar/Adachi-BOT#27]
12.22.1和12.13.1都无法使用

**Comment by SilveryStar** [comment]
不低于 `Node.js v12.16` 应该就能用，请贴出错误信息

**Comment by Annabel0530** [comment]
![J{S3}`8S48X85Q8~@(B3I 9](https://user-images.githubusercontent.com/40524485/125988099-8b2a4354-ec11-48c3-a035-4adfb138a6fe.png)

**Comment by SilveryStar** [comment]
这是没开数据库……请自行启动 Redis 数据库或使用 Docker 运行

**Comment by Annabel0530** [comment]
看漏了 已解决
