### ISSUE TITLE
玩家信息不显示玩家等级

### ISSUE THREAD

**Issue by Annabel0530** [SilveryStar/Adachi-BOT#28]
![2L(6$9CYP1 }{5FPGJZAJ_L](https://user-images.githubusercontent.com/40524485/126035503-dd0166c6-c958-48fd-ac4f-26de651d92da.png)
![5c48e7d267e7e27a22255d3c9e334932](https://user-images.githubusercontent.com/40524485/126035510-464d7fe3-4485-435d-b75b-40daae6beae9.png)
![M}R$7Z3MM_7NE%5KI~X~ 1S](https://user-images.githubusercontent.com/40524485/126035513-0991a2c8-4901-441b-9690-453da57da49e.png)
其他功能正常运行

**Comment by SilveryStar** [comment]
mys有等级，uid没有，接口里没这个信息
