### ISSUE TITLE
群聊回复问题

### ISSUE THREAD

**Issue by TimeRainStarSky** [SilveryStar/Adachi-BOT#286]
### 系统版本

docker

### Node.js 版本

docker

### 应用版本

2.4.12-fix2

### 启动方式

Docker

### 复述操作

Bot在群里一直回复`指令参数错误 ~ `和`角色卡池暂未开放，请在游戏内卡池开放后再尝试`，影响正常聊天

**Comment by MarryDream** [comment]
已修复，更新到最新版试试，没问题的话可以关掉了
