### ISSUE TITLE
派蒙很好，群里已经炸了~

### ISSUE THREAD

**Issue by paiky** [SilveryStar/Adachi-BOT#29]
流量大时图片显示会出问题，不过已经很强啦👍

**Comment by SilveryStar** [comment]
什么问题啊……

**Comment by paiky** [comment]
没事没事，我意思是说群很活跃，没别意思就评论一下.....QAQ

**Comment by SilveryStar** [comment]
:joy:

**Comment by MiniGrayGay** [comment]
> 什么问题啊……

就是发图片过多的时候，发出来的图片有时候会裂开看不了

**Comment by paiky** [comment]
> > 什么问题啊……
> 
> 就是发图片过多的时候，发出来的图片有时候会裂开看不了

挺正常的，作者自己的服务器吧，各种优化没做的话，接口流量大就这样
