### ISSUE TITLE
祈愿十连功能报错，并且角色信息卡片显示位置有误

### ISSUE THREAD

**Issue by Mei-Sakura** [SilveryStar/Adachi-BOT#3]
gacha功能报错，应该是代码问题，更换运行环境也报错。
![1](https://user-images.githubusercontent.com/81066884/116295930-33d9a280-a7cc-11eb-8a81-e42e00edd50e.png)
![2](https://user-images.githubusercontent.com/81066884/116295943-36d49300-a7cc-11eb-9db6-24e8a7d86e20.png)

另外某些uid的角色卡片uid数字显示位置有误。如100038494
![3](https://user-images.githubusercontent.com/81066884/116296106-66839b00-a7cc-11eb-824f-225bf78c20b4.png)

**Comment by SilveryStar** [comment]
Q1. 该问题是4:00a.m.检测自动更新卡池信息时产生，当时角色祈愿与武器祈愿已经结束，出现错误，可以通过重启解决。代码层面将在后续更新
Q2. 已修复 4ded6bd895321b4124e429b1dc4fba38b530aaab
