### ISSUE TITLE
发送消息失败后报错卡死

### ISSUE THREAD

**Issue by MiniGrayGay** [SilveryStar/Adachi-BOT#30]
发送消息遇到错误代码120之后报错如图
![image](https://user-images.githubusercontent.com/64829926/126248726-3c4f578b-aadd-4406-b375-2d6561bf8522.png)

**Comment by MiniGrayGay** [comment]
禁言状态有人发命令，带图片的回复就会报错120，并且机器人掉线，然后掉线重登（多人发指令这边发不出图片）就会nodejs卡掉了（大佬怎么退群了）
![image](https://user-images.githubusercontent.com/64829926/126254383-ad023f4f-6780-4040-95b4-2417a05832f8.png)

**Comment by SilveryStar** [comment]
加了个被禁言过滤，应该没问题了

**Comment by MiniGrayGay** [comment]
okok，晚上我试试
