### ISSUE TITLE
机器人最近出错崩掉的频率有点高

### ISSUE THREAD

**Issue by MiniGrayGay** [SilveryStar/Adachi-BOT#32]
![G08WV0DRS@QL8`FD`W3RB 0](https://user-images.githubusercontent.com/64829926/126889734-c7341af6-1247-4932-bafc-b30e5e110adf.jpg)

大佬，错误如图

**Comment by SilveryStar** [comment]
只看得出是堆内存溢出，具体位置不详，较大可能是 `puppeteer` 造成的（但是查 issues 没找到类似问题），不清楚是不是你那用户太多的原因，我这跑一个月都没事
用 `node --max-old-space-size=4096 -r ts-node/register app.ts` 试试吧

**Comment by MiniGrayGay** [comment]
好的好的，那可能是群太多了，机器是4和8G的，`--max-old-space-size=4096` 需要改到6G吗？

**Comment by SilveryStar** [comment]
应该不用那么多吧2333
