### ISSUE TITLE
带佬，需要增加消息【强制分片发送】规避风控，以及登录协议的切换能不能整合进setting.yml里面

### ISSUE THREAD

**Issue by 530647726** [SilveryStar/Adachi-BOT#34]
如题

**Comment by 530647726** [comment]
另外，登录时可否新增扫码登录。

【十连】也应该内置大概3-5秒的CDw~

**Comment by 530647726** [comment]
使用UID查询后，bot回复应该@查询人（十年问题人不请自来

**Comment by SilveryStar** [comment]
1. 关于风控问题，参考[源码注释](https://github.com/takayama-lily/oicq/blob/6e9b9695b7f4b6b7c2eb9da439bcd86c128da93e/index.d.ts#L22)，在被风控时默认分片发送，新设备/低级账号会出现较多风控问题，多挂几天就好了
2. 关于登录协议，框架( `oicq` )不含协议选项，仅能配置登录设备 `platform`
3. 扫码登录已更新 db0ddee54bbdf7384e80774f68c2e906fd1b16fd，在 `setting.yml` 中配置，但是不建议使用该途径在服务器中部署
4. 响应cd已更新 0493bf3e3c1e16fbddcd0b51a95a50fccd6df4bd，在 `setting.yml` 中配置 `intervalTime`  ，对所有命令生效
5. at用户已更新 e3f946017c82925debb790ec1fcd5b23a66cb7b8，在 `setting.yml` 中配置 `atUser` ，对所有命令生效

**Comment by 530647726** [comment]
牛蛙 mua

**Comment by HYTT0510** [comment]
你好请问一下您这边bot在跑不  我有几个问题想请教一下
