### ISSUE TITLE
mys生成的图片里尘歌壶妙香林背景图片显示ERROR

### ISSUE THREAD

**Issue by itvitv** [SilveryStar/Adachi-BOT#349]
### 系统版本

Ubuntu22.04

### 应用版本

2.9.12

### 启动方式

Docker

### 复述操作

mys生成的图片里尘歌壶妙香林背景图片显示ERROR
不知道是我个人的问题，还是程序bug
截图

![000](https://github.com/SilveryStar/Adachi-BOT/assets/141475752/ae1a11e4-9338-4c66-9f6a-96f7a0c70436)

**Comment by MarryDream** [comment]
图片遗漏了，刚上传，再试试吧。不需要更新
