### ISSUE TITLE
破魔之弓数据错误

### ISSUE THREAD

**Issue by 490720818** [SilveryStar/Adachi-BOT#39]
http://adachi-bot.oss-cn-beijing.aliyuncs.com/Version2/info/docs/%E7%A0%B4%E9%AD%94%E4%B9%8B%E5%BC%93.json
![MOPHLXC8XLBYUHE3DW%7X_B](https://user-images.githubusercontent.com/33067490/127423799-dbead623-85a0-45a5-b632-c0c17069e1e1.gif)

**Comment by SilveryStar** [comment]
fix
