### ISSUE TITLE
图片获取有问题

### ISSUE THREAD

**Issue by MiniGrayGay** [SilveryStar/Adachi-BOT#4]
![image](https://user-images.githubusercontent.com/64829926/117559978-6339ba80-b0bc-11eb-960c-405bd675e561.png)
 最近访问项目图片OSS的网络不太好，经常这样加载不出图片，能不能提供一下本地图片

**Comment by SilveryStar** [comment]
这应该不是网络问题，该界面 (`genshin-info`) 在新版本中已经更改，oss 资源名称有所变化，请更新 `bot` 版本
