### ISSUE TITLE
给bot发送指令不响应

### ISSUE THREAD

**Issue by MUKAPP** [SilveryStar/Adachi-BOT#40]
私聊还是群里都是一样的，搞不太懂…
```
{"log":"\u001b[90m[2021-07-30T12:54:28.550] [MARK] [Android:QQ] - \u001b[39m----------\n","stream":"stdout","time":"2021-07-30T12:54:28.551232788Z"}
{"log":"\u001b[90m[2021-07-30T12:54:28.551] [MARK] [Android:QQ] - \u001b[39mPackage Version: oicq@1.18.3 (Released on 2021/7/22)\n","stream":"stdout","time":"2021-07-30T12:54:28.551312617Z"}
{"log":"\u001b[90m[2021-07-30T12:54:28.551] [MARK] [Android:QQ] - \u001b[39mView Changelogs：https://github.com/takayama-lily/oicq/releases\n","stream":"stdout","time":"2021-07-30T12:54:28.551330229Z"}
{"log":"\u001b[90m[2021-07-30T12:54:28.551] [MARK] [Android:QQ] - \u001b[39m----------\n","stream":"stdout","time":"2021-07-30T12:54:28.551363849Z"}
{"log":"\u001b[90m[2021-07-30T12:54:28.552] [MARK] [Android:QQ] - \u001b[39m正在探索可用服务器...\n","stream":"stdout","time":"2021-07-30T12:54:28.552788171Z"}
{"log":"\u001b[32m[2021-07-30T12:54:29.066] [INFO] [Android:QQ] - \u001b[39m插件 @auth 已成功加载\n","stream":"stdout","time":"2021-07-30T12:54:29.070882007Z"}
{"log":"\u001b[32m[2021-07-30T12:54:29.248] [INFO] [Android:QQ] - \u001b[39m插件 @help 已成功加载\n","stream":"stdout","time":"2021-07-30T12:54:29.249927229Z"}
{"log":"\u001b[32m[2021-07-30T12:54:30.368] [INFO] [Android:QQ] - \u001b[39mRedis 数据库已连接\n","stream":"stdout","time":"2021-07-30T12:54:30.369086451Z"}
{"log":"\u001b[36m[2021-07-30T12:54:30.446] [DEBUG] [Android:QQ] - \u001b[39m{\n","stream":"stdout","time":"2021-07-30T12:54:30.446884274Z"}
{"log":"  '203.205.232.55': 443,\n","stream":"stdout","time":"2021-07-30T12:54:30.446908242Z"}
{"log":"  '203.205.255.221': 443,\n","stream":"stdout","time":"2021-07-30T12:54:30.446915262Z"}
{"log":"  '203.205.255.220': 8080\n","stream":"stdout","time":"2021-07-30T12:54:30.446918255Z"}
{"log":"}\n","stream":"stdout","time":"2021-07-30T12:54:30.446921071Z"}
{"log":"\u001b[90m[2021-07-30T12:54:30.447] [MARK] [Android:QQ] - \u001b[39mconnecting to 203.205.232.55:443\n","stream":"stdout","time":"2021-07-30T12:54:30.447263478Z"}
{"log":"\u001b[90m[2021-07-30T12:54:30.451] [MARK] [Android:QQ] - \u001b[39m203.205.232.55:443 connected\n","stream":"stdout","time":"2021-07-30T12:54:30.451894173Z"}
{"log":"\u001b[90m[2021-07-30T12:54:30.912] [MARK] [Android:QQ] - \u001b[39mWelcome, MUK的稽器人 ! 初始化资源...\n","stream":"stdout","time":"2021-07-30T12:54:30.912865881Z"}
{"log":"\u001b[32m[2021-07-30T12:54:30.986] [INFO] [Android:QQ] - \u001b[39mExpress 服务器已启动\n","stream":"stdout","time":"2021-07-30T12:54:30.986707591Z"}
{"log":"\u001b[32m[2021-07-30T12:54:31.771] [INFO] [Android:QQ] - \u001b[39m插件 genshin 已成功加载\n","stream":"stdout","time":"2021-07-30T12:54:31.771296081Z"}
{"log":"\u001b[32m[2021-07-30T12:54:31.942] [INFO] [Android:QQ] - \u001b[39m插件 tools 已成功加载\n","stream":"stdout","time":"2021-07-30T12:54:31.944969571Z"}
{"log":"\u001b[90m[2021-07-30T12:54:31.956] [MARK] [Android:QQ] - \u001b[39m加载了3个好友，9个群。\n","stream":"stdout","time":"2021-07-30T12:54:31.956925493Z"}
{"log":"\u001b[90m[2021-07-30T12:54:31.956] [MARK] [Android:QQ] - \u001b[39m初始化完毕，开始处理消息。\n","stream":"stdout","time":"2021-07-30T12:54:31.956946956Z"}

{"log":"\u001b[32m[2021-07-30T13:02:27.777] [INFO] [Android:QQ] - \u001b[39mrecv from: [Private: QQ(friend)] help\n","stream":"stdout","time":"2021-07-30T13:02:27.777703575Z"}
```

**Comment by GaussYuan191** [comment]
可以输入help 看提示 比如说查刻晴信息 输入 info 刻晴 就有了

**Comment by GaussYuan191** [comment]
我现在的问题是 通过UID 查询的时候 米游社接口报错：please login

**Comment by SilveryStar** [comment]
> 我现在的问题是 通过UID 查询的时候 米游社接口报错：please login

请配置 cookies.yml ，信息查询需要米游社 cookie 才能执行

**Comment by SilveryStar** [comment]
> 私聊还是群里都是一样的，搞不太懂…
> 
> ```
> {"log":"\u001b[90m[2021-07-30T12:54:28.550] [MARK] [Android:QQ] - \u001b[39m----------\n","stream":"stdout","time":"2021-07-30T12:54:28.551232788Z"}
> {"log":"\u001b[90m[2021-07-30T12:54:28.551] [MARK] [Android:QQ] - \u001b[39mPackage Version: oicq@1.18.3 (Released on 2021/7/22)\n","stream":"stdout","time":"2021-07-30T12:54:28.551312617Z"}
> {"log":"\u001b[90m[2021-07-30T12:54:28.551] [MARK] [Android:QQ] - \u001b[39mView Changelogs：https://github.com/takayama-lily/oicq/releases\n","stream":"stdout","time":"2021-07-30T12:54:28.551330229Z"}
> {"log":"\u001b[90m[2021-07-30T12:54:28.551] [MARK] [Android:QQ] - \u001b[39m----------\n","stream":"stdout","time":"2021-07-30T12:54:28.551363849Z"}
> {"log":"\u001b[90m[2021-07-30T12:54:28.552] [MARK] [Android:QQ] - \u001b[39m正在探索可用服务器...\n","stream":"stdout","time":"2021-07-30T12:54:28.552788171Z"}
> {"log":"\u001b[32m[2021-07-30T12:54:29.066] [INFO] [Android:QQ] - \u001b[39m插件 @auth 已成功加载\n","stream":"stdout","time":"2021-07-30T12:54:29.070882007Z"}
> {"log":"\u001b[32m[2021-07-30T12:54:29.248] [INFO] [Android:QQ] - \u001b[39m插件 @help 已成功加载\n","stream":"stdout","time":"2021-07-30T12:54:29.249927229Z"}
> {"log":"\u001b[32m[2021-07-30T12:54:30.368] [INFO] [Android:QQ] - \u001b[39mRedis 数据库已连接\n","stream":"stdout","time":"2021-07-30T12:54:30.369086451Z"}
> {"log":"\u001b[36m[2021-07-30T12:54:30.446] [DEBUG] [Android:QQ] - \u001b[39m{\n","stream":"stdout","time":"2021-07-30T12:54:30.446884274Z"}
> {"log":"  '203.205.232.55': 443,\n","stream":"stdout","time":"2021-07-30T12:54:30.446908242Z"}
> {"log":"  '203.205.255.221': 443,\n","stream":"stdout","time":"2021-07-30T12:54:30.446915262Z"}
> {"log":"  '203.205.255.220': 8080\n","stream":"stdout","time":"2021-07-30T12:54:30.446918255Z"}
> {"log":"}\n","stream":"stdout","time":"2021-07-30T12:54:30.446921071Z"}
> {"log":"\u001b[90m[2021-07-30T12:54:30.447] [MARK] [Android:QQ] - \u001b[39mconnecting to 203.205.232.55:443\n","stream":"stdout","time":"2021-07-30T12:54:30.447263478Z"}
> {"log":"\u001b[90m[2021-07-30T12:54:30.451] [MARK] [Android:QQ] - \u001b[39m203.205.232.55:443 connected\n","stream":"stdout","time":"2021-07-30T12:54:30.451894173Z"}
> {"log":"\u001b[90m[2021-07-30T12:54:30.912] [MARK] [Android:QQ] - \u001b[39mWelcome, MUK的稽器人 ! 初始化资源...\n","stream":"stdout","time":"2021-07-30T12:54:30.912865881Z"}
> {"log":"\u001b[32m[2021-07-30T12:54:30.986] [INFO] [Android:QQ] - \u001b[39mExpress 服务器已启动\n","stream":"stdout","time":"2021-07-30T12:54:30.986707591Z"}
> {"log":"\u001b[32m[2021-07-30T12:54:31.771] [INFO] [Android:QQ] - \u001b[39m插件 genshin 已成功加载\n","stream":"stdout","time":"2021-07-30T12:54:31.771296081Z"}
> {"log":"\u001b[32m[2021-07-30T12:54:31.942] [INFO] [Android:QQ] - \u001b[39m插件 tools 已成功加载\n","stream":"stdout","time":"2021-07-30T12:54:31.944969571Z"}
> {"log":"\u001b[90m[2021-07-30T12:54:31.956] [MARK] [Android:QQ] - \u001b[39m加载了3个好友，9个群。\n","stream":"stdout","time":"2021-07-30T12:54:31.956925493Z"}
> {"log":"\u001b[90m[2021-07-30T12:54:31.956] [MARK] [Android:QQ] - \u001b[39m初始化完毕，开始处理消息。\n","stream":"stdout","time":"2021-07-30T12:54:31.956946956Z"}
> 
> {"log":"\u001b[32m[2021-07-30T13:02:27.777] [INFO] [Android:QQ] - \u001b[39mrecv from: [Private: QQ(friend)] help\n","stream":"stdout","time":"2021-07-30T13:02:27.777703575Z"}
> ```

请贴出你的 setting.yml

**Comment by MUKAPP** [comment]
> > 私聊还是群里都是一样的，搞不太懂…
> > ```
> > {"log":"\u001b[90m[2021-07-30T12:54:28.550] [MARK] [Android:QQ] - \u001b[39m----------\n","stream":"stdout","time":"2021-07-30T12:54:28.551232788Z"}
> > {"log":"\u001b[90m[2021-07-30T12:54:28.551] [MARK] [Android:QQ] - \u001b[39mPackage Version: oicq@1.18.3 (Released on 2021/7/22)\n","stream":"stdout","time":"2021-07-30T12:54:28.551312617Z"}
> > {"log":"\u001b[90m[2021-07-30T12:54:28.551] [MARK] [Android:QQ] - \u001b[39mView Changelogs：https://github.com/takayama-lily/oicq/releases\n","stream":"stdout","time":"2021-07-30T12:54:28.551330229Z"}
> > {"log":"\u001b[90m[2021-07-30T12:54:28.551] [MARK] [Android:QQ] - \u001b[39m----------\n","stream":"stdout","time":"2021-07-30T12:54:28.551363849Z"}
> > {"log":"\u001b[90m[2021-07-30T12:54:28.552] [MARK] [Android:QQ] - \u001b[39m正在探索可用服务器...\n","stream":"stdout","time":"2021-07-30T12:54:28.552788171Z"}
> > {"log":"\u001b[32m[2021-07-30T12:54:29.066] [INFO] [Android:QQ] - \u001b[39m插件 @auth 已成功加载\n","stream":"stdout","time":"2021-07-30T12:54:29.070882007Z"}
> > {"log":"\u001b[32m[2021-07-30T12:54:29.248] [INFO] [Android:QQ] - \u001b[39m插件 @help 已成功加载\n","stream":"stdout","time":"2021-07-30T12:54:29.249927229Z"}
> > {"log":"\u001b[32m[2021-07-30T12:54:30.368] [INFO] [Android:QQ] - \u001b[39mRedis 数据库已连接\n","stream":"stdout","time":"2021-07-30T12:54:30.369086451Z"}
> > {"log":"\u001b[36m[2021-07-30T12:54:30.446] [DEBUG] [Android:QQ] - \u001b[39m{\n","stream":"stdout","time":"2021-07-30T12:54:30.446884274Z"}
> > {"log":"  '203.205.232.55': 443,\n","stream":"stdout","time":"2021-07-30T12:54:30.446908242Z"}
> > {"log":"  '203.205.255.221': 443,\n","stream":"stdout","time":"2021-07-30T12:54:30.446915262Z"}
> > {"log":"  '203.205.255.220': 8080\n","stream":"stdout","time":"2021-07-30T12:54:30.446918255Z"}
> > {"log":"}\n","stream":"stdout","time":"2021-07-30T12:54:30.446921071Z"}
> > {"log":"\u001b[90m[2021-07-30T12:54:30.447] [MARK] [Android:QQ] - \u001b[39mconnecting to 203.205.232.55:443\n","stream":"stdout","time":"2021-07-30T12:54:30.447263478Z"}
> > {"log":"\u001b[90m[2021-07-30T12:54:30.451] [MARK] [Android:QQ] - \u001b[39m203.205.232.55:443 connected\n","stream":"stdout","time":"2021-07-30T12:54:30.451894173Z"}
> > {"log":"\u001b[90m[2021-07-30T12:54:30.912] [MARK] [Android:QQ] - \u001b[39mWelcome, MUK的稽器人 ! 初始化资源...\n","stream":"stdout","time":"2021-07-30T12:54:30.912865881Z"}
> > {"log":"\u001b[32m[2021-07-30T12:54:30.986] [INFO] [Android:QQ] - \u001b[39mExpress 服务器已启动\n","stream":"stdout","time":"2021-07-30T12:54:30.986707591Z"}
> > {"log":"\u001b[32m[2021-07-30T12:54:31.771] [INFO] [Android:QQ] - \u001b[39m插件 genshin 已成功加载\n","stream":"stdout","time":"2021-07-30T12:54:31.771296081Z"}
> > {"log":"\u001b[32m[2021-07-30T12:54:31.942] [INFO] [Android:QQ] - \u001b[39m插件 tools 已成功加载\n","stream":"stdout","time":"2021-07-30T12:54:31.944969571Z"}
> > {"log":"\u001b[90m[2021-07-30T12:54:31.956] [MARK] [Android:QQ] - \u001b[39m加载了3个好友，9个群。\n","stream":"stdout","time":"2021-07-30T12:54:31.956925493Z"}
> > {"log":"\u001b[90m[2021-07-30T12:54:31.956] [MARK] [Android:QQ] - \u001b[39m初始化完毕，开始处理消息。\n","stream":"stdout","time":"2021-07-30T12:54:31.956946956Z"}
> > 
> > {"log":"\u001b[32m[2021-07-30T13:02:27.777] [INFO] [Android:QQ] - \u001b[39mrecv from: [Private: QQ(friend)] help\n","stream":"stdout","time":"2021-07-30T13:02:27.777703575Z"}
> > ```
> 
> 请贴出你的 setting.yml

把settings.yml贴出来才发现问题了。。我之前一直在JuiceSSH用vim改的，因为要复制东西就在宝塔里复制了，发现setting.yml还是很久之前的（但是我在vim里看没问题），可能是我Linux没怎么接触过的原因叭（（（
麻烦大佬了，感谢

**Comment by GaussYuan191** [comment]
root@Gauss:/home/admin/Adachi-BOT-master# npm run serve

> adachi-bot@2.0.5 serve /home/admin/Adachi-BOT-master
> forever start -v -c ts-node app.ts

warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: app.ts
root@Gauss:/home/admin/Adachi-BOT-master# npm run serve

> adachi-bot@2.0.5 serve /home/admin/Adachi-BOT-master
> forever start -v -c ts-node app.ts

运行  npm run serve 这个命令的结果如下 这样好像没有正常运行 这个怎么解决啊 就是没办法永久运行在服务器上
