### ISSUE TITLE
请问下cookies需要填入的格式是?

### ISSUE THREAD

**Issue by Ruoh3kou** [SilveryStar/Adachi-BOT#41]
我按如图填写，启动后输入 uid 相关命令，会提示please login

![image](https://user-images.githubusercontent.com/29646632/127728159-86c0f328-13b8-469b-b424-6b289914ba4d.png)

**Comment by SilveryStar** [comment]
你应该直接把“米游社Cookies(可多个)”替换掉，而不是删除 `-`
```
cookies:
  - xxxx
  - xxxx
```

**Comment by Ruoh3kou** [comment]
> 你应该直接把“米游社Cookies(可多个)”替换掉，而不是删除 `-`
> 
> ```
> cookies:
>   - xxxx
>   - xxxx
> ```

谢谢 已解决
