### ISSUE TITLE
关于部署环境的疑问

### ISSUE THREAD

**Issue by SilveryStar** [SilveryStar/Adachi-BOT#42]
root@Gauss:/home/admin/Adachi-BOT-master# npm run serve

> adachi-bot@2.0.5 serve /home/admin/Adachi-BOT-master
> forever start -v -c ts-node app.ts

warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: app.ts
root@Gauss:/home/admin/Adachi-BOT-master# npm run serve

> adachi-bot@2.0.5 serve /home/admin/Adachi-BOT-master
> forever start -v -c ts-node app.ts

运行  npm run serve 这个命令的结果如下 这样好像没有正常运行 这个怎么解决啊 就是没办法永久运行在服务器上

_Originally posted by @GaussYuan191 in https://github.com/SilveryStar/Adachi-BOT/issues/40#issuecomment-890318656_

**Comment by SilveryStar** [comment]
@GaussYuan191 首先请您在使用过程中遇到问题时，新建自己的 issue 而非在他人发起的 issue 或已关闭的 issue 下提问
关于你的疑问
```
warn: --minUptime not set. Defaulting to: 1000ms
warn: --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info: Forever processing file: app.ts
```
以上报告为正常运行，使用 `forever list` 可查看后台运行的程序

**Comment by GaussYuan191** [comment]
感谢大佬抽时间回答 问题解决了 sudo npm install forever -g   #安装forever 再用forever list 就能看了 如果不能启动 试下重启服务器再运行 停止运行 可以直接杀死进程
