### ISSUE TITLE
现在这个BOT没插件吗

### ISSUE THREAD

**Issue by MUKAPP** [SilveryStar/Adachi-BOT#43]
如题，挺好一原神bot但是只能当原神bot…
虽然说我也是开发者但是我不会JavaScript呜呜

**Comment by SilveryStar** [comment]
手里还有别的东西要写，近一段时间内没有开发插件的计划（也没什么想写的），只能说欢迎开发者贡献代码了（趴

**Comment by MUKAPP** [comment]
> 手里还有别的东西要写，近一段时间内没有开发插件的计划（也没什么想写的），只能说欢迎开发者贡献代码了（趴

好的叭…那这个bot没有群什么的嘛

**Comment by MUKAPP** [comment]
一开始还以为那个ban是禁言，试了一下才发现是我想错了（（

**Comment by SilveryStar** [comment]
没群，有疑问发 issue

**Comment by MUKAPP** [comment]
> 没群，有疑问发 issue

好的叭，感谢大佬
