### ISSUE TITLE
在登录时提示无法登录

### ISSUE THREAD

**Issue by HYTT0510** [SilveryStar/Adachi-BOT#44]
[禁止登录]当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。(错误码：237)
以及询问一下cookies格式
谢谢大佬回答！

**Comment by SilveryStar** [comment]
账号等级较低在服务器上可能长时间无法登陆，建议更换较高级的账号，或者等一段时间再试
cookies 格式为 README 中将 "米游社Cookies(可多个)" 替换为 米游社cookie 需保留 `-`，即
```yml
cookies:
  - xxxxx
  - yyyyy
```

**Comment by HYTT0510** [comment]
你好  我尝试了我自己的qq也是提示无法登录   请问是否需要多次尝试？
以及米游社的cookies是哪一项？还是完整的cookie

**Comment by SilveryStar** [comment]
异地登陆什么时候能登上还是比较随缘（，可以多试试
cookie是完整的

**Comment by HYTT0510** [comment]
好的  谢谢您的回答
