### ISSUE TITLE
关于扫码登录后的问题

### ISSUE THREAD

**Issue by HYTT0510** [SilveryStar/Adachi-BOT#45]
请问在扫码登录后  手机上显示已成功   但是在服务器上无反应是什么问题
以及platform: 1    但是在登录时显示是安卓手表  是否是我的配置有问题
![image](https://user-images.githubusercontent.com/46914653/128352106-f4a1399e-f6fc-47bf-9677-1bb9ef7b7d6e.png)

**Comment by SilveryStar** [comment]
实际登录平台仍是手机，成功后按 Enter 手机端出现下线通知才算登陆成功

**Comment by HYTT0510** [comment]
我这边扫码登录之后   手机显示成功  但是按enter无反应

**Comment by SilveryStar** [comment]
请发终端输出日志

**Comment by wanghao-desu** [comment]
![image](https://user-images.githubusercontent.com/66713455/128382601-ffb8324e-d597-45fd-a996-c193a2b06367.png)
 请问我这里已经登上qq了 但是发指令没有什么反应啊 可能是哪里出问题了啊

**Comment by HYTT0510** [comment]
![image](https://user-images.githubusercontent.com/46914653/128382860-337c72e4-f31a-4181-a214-690355e5bb6a.png)

**Comment by SilveryStar** [comment]
> ![image](https://user-images.githubusercontent.com/66713455/128382601-ffb8324e-d597-45fd-a996-c193a2b06367.png)
> 请问我这里已经登上qq了 但是发指令没有什么反应啊 可能是哪里出问题了啊

新建 issue 并附上 setting.yml 的内容，请勿在其他 issue 内提问

**Comment by HYTT0510** [comment]
你好可否有偿帮忙远程部署一下  谢谢！

**Comment by HYTT0510** [comment]
[68fd0f1b402eb0db92fe0803ebd708dd07e7fdecbcd6be072262b2205a350fd0-json.log](https://github.com/SilveryStar/Adachi-BOT/files/6940098/68fd0f1b402eb0db92fe0803ebd708dd07e7fdecbcd6be072262b2205a350fd0-json.log)

**Comment by HYTT0510** [comment]
![image](https://user-images.githubusercontent.com/46914653/128384249-55e951b6-f7f6-4781-8cc8-6e4608c0eea4.png)
z这是最后的操作  手机qq点了确定之后   显示登陆成功 但是并未下线

**Comment by SilveryStar** [comment]
用 login 按 enter 没反应是正常的，因为扫码登录需要每次验证，不能用 docker 启动，所以没有做适配
docker 部署请使用密码登录

**Comment by HYTT0510** [comment]
如果我再武汉使用的是在杭州的服务器  我的账号需要在哪里进行登录才可以使用密码正常登录呢？

**Comment by SilveryStar** [comment]
这个只能问tx……我的账号差不多两天登上的，或者检查设备锁是否关闭了

**Comment by HYTT0510** [comment]
你好  我看了您使用的机器人框架   他有一个apk可以解决登录问题  但是我在登录之后可以接受消息 但是并不发言  请问是什么问题  或者配置错误？  我的header是空字符串

**Comment by SilveryStar** [comment]
发一下setting和日志

**Comment by HYTT0510** [comment]
![KD6U{0~K%Q$Q1@7SUIBJL2O](https://user-images.githubusercontent.com/46914653/128600110-a667f3ba-c087-4e70-9905-a41e9b8e2e02.png)
![HP9CI}AE6 `)YG_E_D4JWHS](https://user-images.githubusercontent.com/46914653/128600114-b7b081ad-9dea-4a80-9b71-04841c6921ab.png)

**Comment by SilveryStar** [comment]
报错 ECONNRESET，没连接上，应该是qq服务器那边关闭了连接

**Comment by HYTT0510** [comment]
请问这种情况需要怎么解决呢   能收信息   不回信息

**Comment by SilveryStar** [comment]
检查网络/换forever启动/docker启动用密码登录，还有你 cookies 格式有问题

**Comment by HYTT0510** [comment]
1，请问forever # 生成配置文件模板  这一步如何实现
![Uploading image.png…]()

2，cookies 我是使用cookie-editor提取的完整cookies，格式是否有问题？
![image](https://user-images.githubusercontent.com/46914653/128604315-0090d65d-c6ca-4d3f-897c-1d9e27345d02.png)

**Comment by SilveryStar** [comment]
上面的报错的没开redis数据库，可以用下面的命令启动
```
docker pull redis
docker run -d -p 6379:56379 --name bot-redis -v 指定本地绝对目录:/data redis --appendonly yes
```
另外，完整的cookie指的是一个完整的字符串，不是json串……

**Comment by HYTT0510** [comment]
你好 请问本地绝对路径是安装目录还是自己指定一个    
 在执行第二个命令时报错  
 root@TTTT:~/Adachi-BOT# docker run -d -p 6379:56379 --name bot-redis -v /root/tttt:/data redis --appendonly yes
docker: Error response from daemon: Conflict. The container name "/bot-redis" is already in use by container "718c5c307a22fd91401dffe113986a221a74a870f248b666098a36bc7abb7987". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

**Comment by SilveryStar** [comment]
拜托你稍微读一读报错的信息是什么意思再问……
docker ps -a 查看启动的容器，bot-redis 已经创建过了，718c5c307a22 是这个容器的id，docker start 718c5c307a22 来启动这个容器就行

**Comment by HYTT0510** [comment]
不好意思因为是第一次接触linux以及做这种项目所以一直麻烦您
redis连接成功后再次npm run start报错
![image](https://user-images.githubusercontent.com/46914653/128611601-67d6157b-084a-4c90-9f20-914bf67f2c6d.png)
![image](https://user-images.githubusercontent.com/46914653/128611610-89f04638-08fd-4e4e-9f91-43e68551ea62.png)

**Comment by SilveryStar** [comment]
看不出具体原因，先重启服务器然后 `forever list` 和 `docker ps -a` 检查进程和容器情况，启动 redis 后再运行程序试试

**Comment by HYTT0510** [comment]
重启之后再按顺序运行  依然报错  
![image](https://user-images.githubusercontent.com/46914653/128612428-de639e1d-2b89-4d73-b63b-ffef0b5106e9.png)
![image](https://user-images.githubusercontent.com/46914653/128612431-0f38a1d7-5929-4e8b-ae29-28cc4c3be7e0.png)

**Comment by SilveryStar** [comment]
我知道了，之前的 redis 给 docker 用的没映射端口
```
forever stop 1630
docker stop 7f6052034b64
docker rm 7f6052034b64
docker run -d -p 6379:56379 --name bot-redis -v /root/redis/data:/data redis --appendonly yes
npm start
```

**Comment by HYTT0510** [comment]
此报错已解决  但是因为我使用6379端口  报被占用  于是我更改了 redis.conf 中 6379→6377     setting.yml中56379→56377   
![image](https://user-images.githubusercontent.com/46914653/128612924-51649bc8-03b1-4fea-b86a-cf63ffd73ed0.png)
此问题是否与端口有关

**Comment by SilveryStar** [comment]
命令启动不管 redis,conf ，要删除之前的容器然后运行
docker run -d -p 56377:6379 --name test-redis -v /root/redis/data:/data redis --appendonly yes

**Comment by HYTT0510** [comment]
你好 以上问题已解决   使用时有两个问题
1，提示米游社接口报错: Please login  cookies截图附上
![image](https://user-images.githubusercontent.com/46914653/128613838-7b337fcf-fd1c-4b3f-a555-64fa3dc11a93.png)

2，无法发送图片
![JF}O07X97IU)$_DCEP{PT(I](https://user-images.githubusercontent.com/46914653/128613851-ba1e6b21-06a7-4924-9feb-0312c35253d9.png)

**Comment by SilveryStar** [comment]
1 断线后保留一个空格
2 仍然是风控问题，挂一段时间能解决
3 我允许bot的服务器是阿里云学生机，在只运行这一个服务的情况下

**Comment by HYTT0510** [comment]
你好再请问两个问题
1，使用forever模块  是首先运行 foever start config/login.js  再运行npm run serve   ?
2,如果使用npm start启动  一直监管，如果机器人卡住 或者  重新登录   需要怎么重启？

**Comment by SilveryStar** [comment]
login 是 docker 途径启动用来生成设备文件用的，forever 启动不需要这个，只需 `npm run serve`
如果 start 启动的话……直接 Ctrl+C 杀进程就行了，forever 如何关闭后台程序请自行百度

**Comment by HYTT0510** [comment]
我在运行npm run serve后提示
```
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
```

**Comment by SilveryStar** [comment]
这个是正常启动

**Comment by HYTT0510** [comment]
好的  感谢！
另外修改了config/commands.yml  但是群里发送help菜单未变

**Comment by SilveryStar** [comment]
如果确认重启后还是没变，就把日志和配置发出来

**Comment by HYTT0510** [comment]
问题已解决  谢谢大佬的耐心回答！十分感谢！

**Comment by mashirozx** [comment]
> 这个只能问tx……我的账号差不多两天登上的，或者检查设备锁是否关闭了

你好，请问一下是不是收到 `[下线通知]该帐号密码目前已经泄露，请按照系统指引重新登录，为避免产生损失建议及时修改密码。你也可以对帐号进行<TITLE="资金管理",URL="https://myun.tenpay.com/mqq/banneduser/index.shtml?_wv=1027">` 以后，过几天后重启服务就可以了，不用重新验证和登录？

**Comment by SilveryStar** [comment]
> 你好，请问一下是不是收到 `[下线通知]该帐号密码目前已经泄露

麻烦另开 issue ，这个 issue 太旧了

**Comment by mashirozx** [comment]
你好。不好意思，并不是adachi bot的问题，这个问题在OICQ里面已经有报告了：https://github.com/takayama-lily/oicq/issues/212

我只是想问一下你当时“差不多两天登上的”，有没有重新走一遍认证流程？还是说这个异地登录提醒过一段时间就会自动消失？

**Comment by SilveryStar** [comment]
> 我只是想问一下你当时“差不多两天登上的”，有没有重新走一遍认证流程？还是说这个异地登录提醒过一段时间就会自动消失？

没有，就是等一段时间就能登上了

**Comment by mashirozx** [comment]
明白了，非常感谢
