### ISSUE TITLE
关于登录成功，可以正常显示接收的消息，但是没有执行回复操作

### ISSUE THREAD

**Issue by wanghao-desu** [SilveryStar/Adachi-BOT#46]
![image](https://user-images.githubusercontent.com/66713455/128384015-35b148dd-490f-4a97-b3f4-64ffe76ba4f4.png)

**Comment by SilveryStar** [comment]
README 里写了，header 是指令起始符，例如 `/` `$` `#`，你应该设置成这些符号而非单词，在使用指令时前面加上这些符号如 `#info`

**Comment by wanghao-desu** [comment]
![image](https://user-images.githubusercontent.com/66713455/128452589-fd3ba66a-07cb-4f45-b163-ee08b29417a4.png)
![image](https://user-images.githubusercontent.com/66713455/128452627-9114e7b0-5896-4503-91b5-b915187de71e.png)
哈哈 改了header还是没有回复 上面还有一条报错 看不懂是哪里出问题了
