### ISSUE TITLE
Char角色信息新角色图片显示Error

### ISSUE THREAD

**Issue by Lenhee** [SilveryStar/Adachi-BOT#48]
抽卡上午也是显示错误 但是现在正常了 （可能您正在处理中。。。
下面是建议：如果可以的话希望角色名字繁体、甚至是绰号的形式发出也能检测到；可以查询近期深境螺旋战绩信息
![2C8H9MFDTF$KTR$6{6@1CD9](https://user-images.githubusercontent.com/82086359/128889888-2ffa84c7-64fc-4aae-869b-0d201d6c14dc.png)
![RD2OXW%B6QX%`TCDE7DVP}L](https://user-images.githubusercontent.com/82086359/128889907-ae35797d-ea3e-4a29-b221-af747ee42608.png)

**Comment by SilveryStar** [comment]
图片资源已添加
