### ISSUE TITLE
拉取修改后重启bot出现报错，发送指令无响应

### ISSUE THREAD

**Issue by Nigel-NI** [SilveryStar/Adachi-BOT#52]
使用git pull拉取更新后启动bot，出现错误，QQ群内发送指令无响应。
启动时的错误日志如下：
> {"log":"(node:24) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'main' of undefined\n","stream":"stderr","time":"2021-08-13T13:01:01.192609385Z"}
{"log":"    at addPlugin (/bot/src/modules/plugin.ts:56:20)\n","stream":"stderr","time":"2021-08-13T13:01:01.192651468Z"}
{"log":"    at /bot/src/plugins/genshin/init.ts:153:18\n","stream":"stderr","time":"2021-08-13T13:01:01.192670732Z"}
{"log":"    at step (/bot/src/plugins/genshin/init.ts:44:23)\n","stream":"stderr","time":"2021-08-13T13:01:01.192674841Z"}
{"log":"    at Object.next (/bot/src/plugins/genshin/init.ts:25:53)\n","stream":"stderr","time":"2021-08-13T13:01:01.19267863Z"}
{"log":"    at fulfilled (/bot/src/plugins/genshin/init.ts:16:58)\n","stream":"stderr","time":"2021-08-13T13:01:01.192682532Z"}
{"log":"    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n","stream":"stderr","time":"2021-08-13T13:01:01.192686293Z"}
{"log":"(node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)\n","stream":"stderr","time":"2021-08-13T13:01:01.192690207Z"}
{"log":"(node:24) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.\n","stream":"stderr","time":"2021-08-13T13:01:01.192707968Z"}

**Comment by SilveryStar** [comment]
无法复现，原因不明……不过 docker 启动pull 更新要更新镜像，把原镜像删了才行再构建才行，可以尝试重新拉取

**Comment by Nigel-NI** [comment]
我删掉原有的容器、镜像和git，重新拉取试一下吧
