### ISSUE TITLE
执行yarn start抛出异常

### ISSUE THREAD

**Issue by MatchaDog** [SilveryStar/Adachi-BOT#54]
![image](https://user-images.githubusercontent.com/35016589/130038908-dfd6d68e-0442-445a-9d0d-77365f0c21c5.png)
尝试过修改 `redis` 的 `host` or 全局所有的`port` or 重新拉取并启动`docker` 都无效；看log好像是在启动插件 `Genshin` 时抛错的。
请问这种情况该怎么处理呢

**Comment by SilveryStar** [comment]
提供的 docker-compose 启动了 `redis` 和 `bot` 两个容器，不用在使用 `yarn start` 启动
错误原因是其中 `redis` 没有做端口映射，宿主机自然无法连接

**Comment by MatchaDog** [comment]
已解决 感谢
