### ISSUE TITLE
能接收消息，但不回复

### ISSUE THREAD

**Issue by wormtql** [SilveryStar/Adachi-BOT#55]
![image](https://user-images.githubusercontent.com/42363449/131471491-943d5d47-359e-4223-ae8d-3825c55e248a.png)
![image](https://user-images.githubusercontent.com/42363449/131471638-19a7c482-11c4-4df9-b531-91e91943cb33.png)
是使用docker启动的

**Comment by SilveryStar** [comment]
cookies.yml 配置有问题，参考问题汇总q5

**Comment by wormtql** [comment]
![image](https://user-images.githubusercontent.com/42363449/131493191-1afb34e4-536e-41b1-aa3c-d823f1e01154.png)
![image](https://user-images.githubusercontent.com/42363449/131493233-9a8c2bdc-d5b0-4df7-8cdc-01fb08ae1b50.png)
设置cookie后仍然无法回复

**Comment by SilveryStar** [comment]
草，那算你倒霉，明天开服之后再部署吧，现在池子关了这个信息获取不到，以后修

**Comment by SilveryStar** [comment]
错误已修复，请删除本地 docker 容器后重新拉取并构建
