### ISSUE TITLE
查询不到2.1新角色、新武器等有关信息

### ISSUE THREAD

**Issue by Nigel-NI** [SilveryStar/Adachi-BOT#58]
无法查询到雷电将军、九条、薙草之稻光等有关信息，使用指令抽卡时也无法显示相关图片，如图：
![c202837f65ffbe8015c820ccab97934](https://user-images.githubusercontent.com/23294384/131814369-f7f1287d-01aa-4859-a73b-43fa6cff34ff.jpg)

**Comment by SilveryStar** [comment]
大一开学，忙，没空，先等着

**Comment by SilveryStar** [comment]
祈愿图片更新：雷电将军、九条裟罗、珊瑚宫心海、薙草之稻光、不灭月华
info 查询更新：雷电将军、九条裟罗、珊瑚宫心海、埃洛伊、薙草之稻光、「渔获」、不灭月华、衔珠海皇、掠食者
材料更新：天云草实、珊瑚真珠浮游干核、浮游幽核、浮游晶化核、排异之露、雷霆数珠、灰烬之心、狱火之蝶、熔毁之刻
