### ISSUE TITLE
角色面板信息不齐

### ISSUE THREAD

**Issue by MiniGrayGay** [SilveryStar/Adachi-BOT#6]
issue狂魔又双叒叕来了

info缺少旅行者，发空、荧、旅行者都没触发

**Comment by SilveryStar** [comment]
旅行者这个就是单纯的没做，天赋书每种都要，天赋突破材料周本也都有变化。info的这个面板背景是固定的，实在懒得单独整特例了（躺）

**Comment by MiniGrayGay** [comment]
哦哦，好的
