### ISSUE TITLE
推荐一个数据源

### ISSUE THREAD

**Issue by NepPure** [SilveryStar/Adachi-BOT#60]
https://github.com/theBowja/genshin-db/blob/main/examples.md

```js
npm install genshin-db
```

```js
const genshindb = require('genshin-db');
```

应该能减少不少工作量

**Comment by Arondight** [comment]
这个有人也给我推荐过，但是这种东西说不定哪天就不更新了，另外这些数据写起来也还好

**Comment by SilveryStar** [comment]
感谢，不过短时间内不打算换了，自己维护也放心一点

**Comment by NepPure** [comment]
感谢大佬，不知是否能告知 ，物品图片这些数据是来自于哪里的，看代码这一块数据好像并没有开源

**Comment by SilveryStar** [comment]
> 感谢大佬，不知是否能告知 ，物品图片这些数据是来自于哪里的，看代码这一块数据好像并没有开源

在 1.x 版本的 5d7bb4fc56849095c50c0375ed3aa9f66e28f1d8 前图片资源是开源的，此后为因为希望避免游戏版本更新导致需要频繁更新本项目，改用 oss 进行管理，现已将相关内容写入 README.md，如有意愿了解请移步

**Comment by NepPure** [comment]
感谢解答，借大佬的设计改造了一下，用h5绘制确实很方便，非常感谢大佬们的设计

https://genshin-card.neptunia.vip/cards/views/character.html?name=甘雨

https://github.com/NepPure/genshin-card/tree/main/cards/output
