### ISSUE TITLE
【吃什么】，【深渊】查询能加回来吗? 需要添加角色 模糊词/外号/别称 的查询

### ISSUE THREAD

**Issue by DongGua-Jun** [SilveryStar/Adachi-BOT#61]
比如 万叶，外号叶天帝，希望输入查询指令“我的 叶天帝/天帝”也能查询到 ”我的 枫原万叶“ 的信息

此外，这个添加角色外号的操作希望能整合到一个yml  或者 直接新增指令 私聊/群聊bot进行角色外号添加。

❤❤❤❤❤❤

**Comment by SilveryStar** [comment]
中秋以后有添 feat 的计划，现在实在没时间
然后就是【吃什么】是某个 fork 的功能，我这边没写过

**Comment by DongGua-Jun** [comment]
会加就好，未来可妻。

所以【吃什么】直接加回来呗（

**Comment by MiniGrayGay** [comment]
你说的这几个功能是Arondight基于1.4.6版本改的adachi吧

**Comment by SilveryStar** [comment]
深渊查询 和 别名 都完成了，深渊目前还处于回复刷屏状态，等 oicq 的标准实现（时间待定），吃什么这种功能就等以后开 Adachi-Plugin 仓库吧，不想在本体里加
