### ISSUE TITLE
连不上服务器

### ISSUE THREAD

**Issue by 2385706087** [SilveryStar/Adachi-BOT#63]
能接收到qq群消息，但是在启用npm start之后好像找不到服务器，请问怎么解决
Error: connect ECONNREFUSED 127.0.0.1:56379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)

![image](https://user-images.githubusercontent.com/69779315/132994893-63ee343e-11e1-4885-91af-1aea926121e5.png)

**Comment by SilveryStar** [comment]
请右转FAQ

**Comment by 2385706087** [comment]
![image](https://user-images.githubusercontent.com/69779315/133006686-4700e8d2-3baf-4a51-b8a5-ec07ed6737d5.png)
数据库连上了还是有问题

**Comment by 2385706087** [comment]
> 请右转FAQ

已解决。
但是还有 米游社接口报错: invalid request
米游社的接口现在还没法用吗？

**Comment by SilveryStar** [comment]
烦请不要无视我的 issue 模板，功能目前能正常使用，你不告诉我更多信息我也没辙，同时也请不要在已关闭的 issue 中发言
