### ISSUE TITLE
获取信息时候部分内容无法显示

### ISSUE THREAD

**Issue by liuqianpan2008** [SilveryStar/Adachi-BOT#66]
### 环境
- 系统：windows Server2012 R2
- node 版本：node-v14.18.0-x64
- bot 版本：2.0.8

### 操作复述
输入uid100747598宝箱等其他资源不能正常显示
![afa2031e2de00b5ade96fdd617afc181](https://user-images.githubusercontent.com/80571808/135614401-316b1b57-9081-4d1e-b884-b042cb9f931f.png)

### 配置文件
setting.yml
qrcode: false       # 是否启用扫码登录
                    # 每次登录都需验证,Docker启动禁用,默认不启用
number: *# QQ 账号
password: "*"        # QQ 密码
master: *# BOT 持有者账号
header: ""          # 命令起始符(可为空串"")
platform: 1         # 登录平台
                    # 1.安卓手机(默认) 2.aPad 3.安卓手表 4.MacOS 5.iPad
atUser: true        # 是否启用回复时 at 用户,默认关闭
dbPort: 56379       # 数据库端口
                    # 修改该选项需同时修改 redis.conf -> port
intervalTime: 1500  # 指令操作冷却时间,单位毫秒,默认 1500ms

cookies.yml
cookies:
  - 保密
### 错误报告
无错误报告
![image](https://user-images.githubusercontent.com/80571808/135614520-40df380e-5ed9-42f6-8b71-00c28697dbf8.png)

**Comment by SilveryStar** [comment]
已修复，更新即可

**Comment by liuqianpan2008** [comment]
![B@Z4XRL6A%YLV_`8Z8P)WKY](https://user-images.githubusercontent.com/80571808/135627378-fe7b5a7a-ea2a-4c00-a940-75388cf3fd41.gif)
还有深渊
