### ISSUE TITLE
米游社接口报错：Please login是不是cookies过期了。

### ISSUE THREAD

**Issue by Accelerator1213** [SilveryStar/Adachi-BOT#7]
Hi，我在使用的时候提示米游社接口报错:Please login，我觉得可能是cookies过期导致的；

通过米游社的论坛网页抓取的cookies是不是不能直接使用了~

感谢解答~

**Comment by SilveryStar** [comment]
我现在依然能正常使用，可以考虑先更新cookies

**Comment by Accelerator1213** [comment]
我对比了一下之前的Cookies和现在的Cookies发现现在的Cookies比以前短很多，是不是抓取Cookies的时候出现了什么错误。

**Comment by Accelerator1213** [comment]
更换的新的Cookies还是提示Please login，请问还有什么可能性~

**Comment by SilveryStar** [comment]
这个暂时不清楚，我今天晚点对比后再给你回复

**Comment by Accelerator1213** [comment]
好的，谢谢~

**Comment by SilveryStar** [comment]
目前是新旧cookies都能正常查询，新cookies只是多了几个条目（咱也看不懂什么意思），你的问题确实不清楚怎么产生的

**Comment by Accelerator1213** [comment]
好的，我再试试~

**Comment by Accelerator1213** [comment]
发生了一个新的问题，它开始提示[TypeError: Cannot read property '0' of undefined]，这个是什么操作。

**Comment by Accelerator1213** [comment]
目前我将整个目录删除了，使用npm install重新安装了一次，目前提示的错误是上面那个。

**Comment by Accelerator1213** [comment]
辛苦看下你需要的是不是这个~

**Comment by Accelerator1213** [comment]
![Uploading 20210526_Adachi-BOT_Screenshot.png…]()

**Comment by Accelerator1213** [comment]
![20210526_Adachi-BOT_Screenshot](https://user-images.githubusercontent.com/82789349/119586529-79a37e00-bdff-11eb-9789-bc2f425e4fcd.png)


感觉没上传上去的样子- -

**Comment by SilveryStar** [comment]
草 你是不是重新安装之后没写cookies

**Comment by Accelerator1213** [comment]
这个cookies：后面和UM之间是有一个空格的吧？

**Comment by Accelerator1213** [comment]
![20210526_Adachi-BOT_Screenshot](https://user-images.githubusercontent.com/82789349/119593688-f9841500-be0c-11eb-8247-573d7bb06e67.png)


哈哈，我觉得我可能不太适合这个，非专业选手。

**Comment by Accelerator1213** [comment]
第一个你说没写Cookies的是cookies：后面没跟空格的；Please login是带了空格的。

**Comment by SilveryStar** [comment]
你是一直用不这两个指令还是突然不能用了，如果是后者的话我这边确实没办法，如果是前者，请确保配置文件的格式是
```yaml
cookie:
  - xxxx
# 有空格
```
而不是
```yaml
cookie: xxxx
```

**Comment by Accelerator1213** [comment]
看起来是我Cookies格式出现了问题，已解决，感谢~
