### ISSUE TITLE
BOT 功能/改进征集

### ISSUE THREAD

**Issue by SilveryStar** [SilveryStar/Adachi-BOT#70]
# 此 issue 暂时关闭，待项目重构完成后将另开征集

此 issue 用于征集 BOT 的新功能或对现有功能的优化改进意见。本人会对此 Issue 下的所有评论进行评估。新的功能可能会发布在 BOT 本体（当前项目）或[插件库](https://github.com/SilveryStar/Adachi-Plugin)。

## 暂定更新计划
```
* [x] [ v2.2.4 ] 神器定轨
* [x] [ v2.2.4 ] 原神多连抽
* [x] [ v2.2.5 ] at BOT trigger
* [ ] [ v2.2.6 ] 质量参变仪提醒
* [ ] [ v2.2.6 ] 角色信息扩充（基础生命值/防御力）
* [ ] [ v2.2.7 ] 角色好感故事查询
* [ ] [ v2.2.7 ] 圣遗物背景故事查询
* [ ] [ v2.2.8+ ] 原神日历
* [ ] [ v2.2.8+ ] 国际服查询
* [ ] [ 独立项目 ] 自定义卡池
* [ ] [ 待定 ] 旅行者札记
```

**Comment by XingNian-www** [comment]
> > 版本更新后米游社支持查询树脂之类的东西了，希望可以添加个实时树脂功能
> 
> 当你开启便笺时，会看到提示说“该模块仅自己可见”，所以 BOT 无法获取任何人的便笺信息

能获取自己的就行了咯
看别人的也没啥用,想看的人自行提供cookie查询

**Comment by 490720818** [comment]
> > > 版本更新后米游社支持查询树脂之类的东西了，希望可以添加个实时树脂功能
> > 
> > 
> > 当你开启便笺时，会看到提示说“该模块仅自己可见”，所以 BOT 无法获取任何人的便笺信息
> 
> 能获取自己的就行了咯 看别人的也没啥用,想看的人自行提供cookie查询

提供cookie。。不合适吧

**Comment by MiniGrayGay** [comment]
> > > 那查询抽卡记录也都可以这么做 甚至游戏里的更多东西
> > 
> > 
> > 理论是这样，如果知道别的接口的话，不过现在实在没精力了
> > 以后有机会把这套再抽象一下再弄吧
> 
> 这个项目的武器和角色wiki功能很不错，就是我用的hoshinoBot，emmmmmmmm用不了这个功能很可惜

有内鬼，终止交易

**Comment by Lenhee** [comment]
> @Lenhee
> 
> 1. 可以考虑
> 2. 每日素材功能已经有了，还支持个人订阅+私聊提醒
> 3. todo
> 4. 见插件库

效果很棒孩子们很喜欢 不过第4点插件还未发现

**Comment by SilveryStar** [comment]
> 效果很棒孩子们很喜欢 不过第4点插件还未发现

在分支里找 music（

**Comment by Lenhee** [comment]
> > 效果很棒孩子们很喜欢 不过第4点插件还未发现
> 
> 在分支里找 music（

😂看到了 非常感谢

**Comment by tian564159391** [comment]
![T8I}60R5S)XYQ)PLK3R00TI](https://user-images.githubusercontent.com/37993579/139647667-4a0570e6-b4bd-40d2-8437-4e2e32e5a8b2.png)
https://github.com/idlist/2bot-v3 
有没有可能添加上这个2bot的这个语言学习（复读）功能呢（不太懂

**Comment by SilveryStar** [comment]
> 有没有可能添加上这个2bot的这个语言学习（复读）功能呢（不太懂

复读的话是简单的，不过语言学习就比较麻烦了，而且这个项目是依赖于 `koishi` 的，我短时间内没空研究，不太会考虑

**Comment by Annabel0530** [comment]
既然增加了cookie，是否可以帮忙签到米游社呢？

**Comment by SilveryStar** [comment]
> 既然增加了cookie，是否可以帮忙签到米游社呢？

这个是可以考虑的，以后写

**Comment by PenguinCaptain** [comment]
希望图片有海外镜像站，在海外服务器访问https://adachi-bot.oss-cn-beijing.aliyuncs.com/经常timeout

**Comment by DongGua-Jun** [comment]
玩家信息卡片，命座数字显示在角色图像右上角那一版，
好像既不是默认也不是A/B那两款。

**Comment by SilveryStar** [comment]
> 玩家信息卡片，命座数字显示在角色图像右上角那一版， 好像既不是默认也不是A/B那两款。

应该是别的项目的，我这没写过

**Comment by DongGua-Jun** [comment]
> > 玩家信息卡片，命座数字显示在角色图像右上角那一版， 好像既不是默认也不是A/B那两款。
> 
> 应该是别的项目的，我这没写过

坏耶，我记得米游社cookie接口更新前的adachi，就是用的我说的那一款呀

**Comment by SilveryStar** [comment]
> 希望图片有海外镜像站

尽量用国内的云服务器部署吧，海外的镜像站我现在实在没什么精力弄了（捂脸

**Comment by tian564159391** [comment]
可以加入质量参变仪提醒吗？
比如这周我用了输入使用时间，然后让bot记录一下，下周到点了bot会发消息提醒。

**Comment by buzhibujuelb** [comment]
可以加入圣遗物背景故事/角色好感故事查询吗？

**Comment by buzhibujuelb** [comment]
关于抽卡记录查询，像 https://github.com/pcrbot/erinilis-modules/tree/master/genshingachalog 这样支持自己上传 xlsx 文件也是一个办法

**Comment by SilveryStar** [comment]
> 可以加入圣遗物背景故事/角色好感故事查询吗？

可以考虑

**Comment by SilveryStar** [comment]
> 关于抽卡记录查询，这样支持自己上传 xlsx 文件也是一个办法

这就完全没有必要了，因为本身就是处于「既然收集了cookie就能很方便的获取一些数据」这个角度才考虑做参考记录的，如果还需要 xlsx 的话不如直接去现成的平台

**Comment by buzhibujuelb** [comment]
> > 关于抽卡记录查询，这样支持自己上传 xlsx 文件也是一个办法
> 
> 这就完全没有必要了，因为本身就是处于「既然收集了cookie就能很方便的获取一些数据」这个角度才考虑做参考记录的，如果还需要 xlsx 的话不如直接去现成的平台

那只有等实现 cookie 到 authkey 的转换了

**Comment by buzhibujuelb** [comment]
可以加个角色天赋效果查询吗（最好还包括显示生活天赋）以及倍率（容易搞混像阿贝多e吃防御q吃攻击以及早柚回复量e吃精通q吃攻击这种）

**Comment by SilveryStar** [comment]
> 可以加个角色天赋效果查询吗（最好还包括显示生活天赋）以及倍率（容易搞混像阿贝多e吃防御q吃攻击以及早柚回复量e吃精通q吃攻击这种）

这个短时间内应该不会考虑，现在手里事太多了，而且这个东西也不是很好展示

**Comment by Cn7ci4** [comment]
角色信息里面能加上基础生命值和基础防御力吗,有很多吃生命值和防御力的角色,单纯展示一个基础攻击力对这些角色并不友好

**Comment by deYangar** [comment]
能加个深渊角色使用率榜单么
https://spiralabyss.org/zh/floor-12
![QQ截图20211119162830](https://user-images.githubusercontent.com/70438628/142590663-04b6a6d6-7fa2-487d-986e-868bec807a1e.jpg)
样式类似于这样
![QQ图片20211119162905](https://user-images.githubusercontent.com/70438628/142591019-026813b8-db07-4040-a5f5-a4878c698da8.jpg)

**Comment by SilveryStar** [comment]
> 能加个深渊角色使用率榜单么

挺好，可以做，不过得等

**Comment by KazuhaKun** [comment]
能接入国际服也就是Hoyolab吗？

**Comment by MiniGrayGay** [comment]
米游社改版只能查询8个角色了，还有深渊查询无了。感觉UI改一下会比较好看

**Comment by SilveryStar** [comment]
> 米游社改版只能查询8个角色了，还有深渊查询无了。感觉UI改一下会比较好看

我 issue 里发个公告吧，这事有点麻烦了

**Comment by Annabel0530** [comment]
> > 米游社改版只能查询8个角色了，还有深渊查询无了。感觉UI改一下会比较好看
> 
> 我 issue 里发个公告吧，这事有点麻烦了

请问绑定了cookie的用户能否查看自己的全部角色呢

**Comment by SilveryStar** [comment]
> 请问绑定了cookie的用户能否查看自己的全部角色呢

此事移至 #116 讨论

**Comment by Accelerator1213** [comment]
有没有可能加入提瓦特大地图。

我感觉这会是个庞大的工程。

hhhhh

**Comment by SilveryStar** [comment]
> 有没有可能加入提瓦特大地图。

完全不会考虑，一方面是表现形式，如果只是一张大图的话根本没有意义，但qq根本没法支持更细节的操作，另一方面是没有必要

**Comment by tian564159391** [comment]
希望的功能：
1.查询公告/自动推送公告 这个bot插件的功能https://github.com/pcrbot/erinilis-modules/tree/master/egenshin
2.希望能直接50连，100连之类的，比如原神一单，还是上个插件的功能
3.原神日历 https://github.com/NepPure/genshin_calendar
4.新版本后有两个角色池，好像我没找到切换角色池的方式...
5.Web Console有说明书吗.... 
感谢

**Comment by deYangar** [comment]
> 希望的功能： 1.查询公告/自动推送公告 这个bot插件的功能https://github.com/pcrbot/erinilis-modules/tree/master/egenshin 2.希望能直接50连，100连之类的，比如原神一单，还是上个插件的功能 3.原神日历 https://github.com/NepPure/genshin_calendar 4.新版本后有两个角色池，好像我没找到切换角色池的方式... 5.Web Console有说明书吗.... 感谢

更新最新版，help里面有说切换卡池的方式

**Comment by tian564159391** [comment]
> 

好的感谢

**Comment by Accelerator1213** [comment]
能否考虑提供一个Master广播&开发者公告功能，将需要广播的内容对BOT使用指令发送至所有群。

或者给BOT提供一个公告查询的功能，以便于查询Master&开发者需要通知各位用户的注意事项。

**Comment by SilveryStar** [comment]
> 能否考虑提供一个Master广播&开发者公告功能，将需要广播的内容对BOT使用指令发送至所有群。
> 或者给BOT提供一个公告查询的功能，以便于查询Master&开发者需要通知各位用户的注意事项。

其实以前也想过，不过没有很好的实现思路，估计得我自己写一套api了，以后再说，短时间内不会有

**Comment by Accelerator1213** [comment]
![image](https://user-images.githubusercontent.com/82789349/143609004-49dae070-3c20-4e19-af57-0c74bdc7f735.png)

这个能不能顺带给个UID，号码多的时候容易记混……

**Comment by SilveryStar** [comment]
> 这个能不能顺带给个UID，号码多的时候容易记混……

可，今天的更新就加上

**Comment by SilveryStar** [comment]
> 希望的功能： 1.查询公告/自动推送公告 这个bot插件的功能https://github.com/pcrbot/erinilis-modules/tree/master/egenshin 2.希望能直接50连，100连之类的，比如原神一单，还是上个插件的功能 3.原神日历 https://github.com/NepPure/genshin_calendar 4.新版本后有两个角色池，好像我没找到切换角色池的方式... 5.Web Console有说明书吗.... 感谢

web console 的简要说明已经加在文档里了，其他几个功能短期内不会去做，以后可以考虑

**Comment by Annabel0530** [comment]
希望能增加用户对自己玩家信息卡的头像设置（非常喜欢芭芭拉了属于是）或者用QQ头像的方式显示

**Comment by SilveryStar** [comment]
> 希望能增加用户对自己玩家信息卡的头像设置（非常喜欢芭芭拉了属于是）或者用QQ头像的方式显示

emmm，可以在 mys 指令里面加，qq 头像的话打算加进 genshin.yml 的配置，下个版本和 uid 新样式一起更新吧

**Comment by AzusaYukina** [comment]
希望添加材料计算器，很多时候和群友一起讨论的时候去米游社或者 bwiki 还是麻烦很多
（虽然好像用bot的话指令也有点复杂，但是能否考虑这个需求呢）

**Comment by SilveryStar** [comment]
> 希望添加材料计算器，很多时候和群友一起讨论的时候去米游社或者 bwiki 还是麻烦很多 （虽然好像用bot的话指令也有点复杂，但是能否考虑这个需求呢）

bot 输入的话实在太麻烦了吧……就算做也会优先级很低

**Comment by AzusaYukina** [comment]
> > 希望添加材料计算器，很多时候和群友一起讨论的时候去米游社或者 bwiki 还是麻烦很多 （虽然好像用bot的话指令也有点复杂，但是能否考虑这个需求呢）
> 
> bot 输入的话实在太麻烦了吧……就算做也会优先级很低

其实我感觉是处理多条消息容易乱，但是确实不轻松，也不是特别重要的功能

**Comment by BennettChina** [comment]
有没有考虑过@bot然后输入关键词的方式触发相应功能？或者此功能已有而我没发现呢。相对命令的方式，我想还是@机器人加关键词更方便使用，命令越来越多的情况下总是不容易上手使用的。

**Comment by SilveryStar** [comment]
> 有没有考虑过@bot然后输入关键词的方式触发相应功能？

命令本身不就是关键词吗……at bot+关键词+参数 和 header+参数 有什么本质区别吗……

**Comment by BennettChina** [comment]
> > 有没有考虑过@bot然后输入关键词的方式触发相应功能？
> 
> 命令本身不就是关键词吗……at bot+关键词+参数 和 header+参数 有什么本质区别吗……

我上午的时候试图修改了三个功能的type为enquire类时，bot的动作未触发(估计是我没搞对)。你说的header+参数我想我有点明白了，如果这个方式测试后可行的话，目前也算够用了。

@的方式更像是跟人聊天一样，header+参数如果想做到这点不可避免的会误触发bot的动作。

**Comment by SilveryStar** [comment]
> @的方式更像是跟人聊天一样header+参数如果想做到这点不可避免的会误触发bot的动作。

如果你知道 enquire 的话，至少说明你也看了文档了，文档上也写了 type 是不可更改的，这只是一个给程序看的识别字段…… 
因为不同类型的指令有完全不同的匹配逻辑和匹配结果，我不可能有精力给每个指令写每种类型的处理

如果你愿意为 bot 制作插件定制这类功能的话，我可以给你提供 `HackCommand` 这样的类型，来改变已有的指令配置

**Comment by BennettChina** [comment]
> > @的方式更像是跟人聊天一样header+参数如果想做到这点不可避免的会误触发bot的动作。
> 
> 如果你知道 enquire 的话，至少说明你也看了文档了，文档上也写了 type 是不可更改的，这只是一个给程序看的识别字段…… 因为不同类型的指令有完全不同的匹配逻辑和匹配结果，我不可能有精力给每个指令写每种类型的处理
> 
> 如果你愿意为 bot 制作插件定制这类功能的话，我可以给你提供 `HackCommand` 这样的类型，来改变已有的指令配置

不是很熟悉前端这块的内容，我看看如果能搞懂项目的话会试试的。

**Comment by Accelerator1213** [comment]
我一直有个问题……

为什么我看Web Console的日志时间和服务器时间不一致。。

![image](https://user-images.githubusercontent.com/82789349/144389736-3aa6a195-2e13-4b9d-9d98-e34a0851c4ad.png)

**Comment by Annabel0530** [comment]
能否增加通过主人QQ私聊发送指令的方式让BOT刷新配置文件以及缓存？刷新yml文件设置、卡片信息和用户头像这类的内容。

**Comment by SilveryStar** [comment]
> 能否增加通过主人QQ私聊发送指令的方式让BOT刷新配置文件以及缓存？

刷新图片缓存已经在 v2.2.3 更新计划内了，配置文件的话，不太会考虑 setting 的热更新，commands和genshin是可以支持的

**Comment by Annabel0530** [comment]
> > 能否增加通过主人QQ私聊发送指令的方式让BOT刷新配置文件以及缓存？
> 
> 刷新图片缓存已经在 v2.2.3 更新计划内了，配置文件的话，不太会考虑 setting 的热更新，commands和genshin是可以支持的

我也觉得setting不弄好  容易出错  感谢回复🌹

**Comment by VsentCN** [comment]
建议Web Console的日志功能增加是否自动转到最新一条日志内容的开关，方便复制日志内容

**Comment by SilveryStar** [comment]
> 建议Web Console的日志功能增加是否自动转到最新一条日志内容的开关，方便复制日志内容

那不是有个自动置底吗，选择当天就默认开启的，刷新日志的时候会翻到最底下

**Comment by VsentCN** [comment]
> > 建议Web Console的日志功能增加是否自动转到最新一条日志内容的开关，方便复制日志内容
> 
> 那不是有个自动置底吗，选择当天就默认开启的，刷新日志的时候会翻到最底下

刚出的时候这个功能还没实现，我就下意识以为这个按钮没用了，打扰了

**Comment by Atxoed** [comment]
考不考虑加入米游社签到功能和抽卡记录查询功能

**Comment by SilveryStar** [comment]
> 考不考虑加入米游社签到功能和抽卡记录查询功能

上面都有提过。签到打算做，抽卡记录没法做

**Comment by CMHopeSunshine** [comment]
大大，能不能加一个在群聊里bot被艾特时才触发指令？现在好容易误触发

**Comment by SilveryStar** [comment]
> 大大，能不能加一个在群聊里bot被艾特时才触发指令？现在好容易误触发

emmm，这个会考虑，但是短时间内不会做
不过只要你把 `setting.yml` 里的 `header` 设成 `#` 就不会误触了吧……~~你们难不成说话都带井号开头的吗 （x~~

**Comment by huzwu** [comment]
大大，考不考虑出个人物圣遗物主属性推荐（有圣遗物有效词条推荐更好了）。例如说 人物诺艾尔 :防岩暴。胡桃：精火暴（生火暴）芭芭拉：生生治 充生治  可参考https://bbs.nga.cn/read.php?tid=27859119

**Comment by SilveryStar** [comment]
> 大大，考不考虑出个人物圣遗物主属性推荐（有圣遗物有效词条推荐更好了）。例如说 人物诺艾尔 :防岩暴。胡桃：精火暴（生火暴）芭芭拉：生生治 充生治 可参考https://bbs.nga.cn/read.php?tid=27859119
> 
> 大大，还有深渊配队推荐或者深渊使用率榜单（这个国内白榜刚不做了youngmoe.com/team，国外黑榜目测还有 genshin.honeyhunterworld.com/?lang=CHS）

主属性推荐好麻烦啊。拿 `#guide` 将就用吧，有圣遗物推荐（
后面那个之前有计划，因为米游社api变动搁置了，得再观望一下，之前我去黑榜填的时候它还是要我手填数据，听说现在外服深渊能正常查了。反正不是短期内考虑的

**Comment by Accelerator1213** [comment]
> 

我码了个寂寞，群号完全没码哈哈哈哈哈哈哈哈。

**Comment by SilveryStar** [comment]
@Accelerator1213 问题请新建issue，不要在这里问 ~~上次也是你在这问问题~~

**Comment by Accelerator1213** [comment]
> @Accelerator1213 问题请新建issue，不要在这里问 ~上次也是你在这问问题~

感觉如果是自己配置的时候搞错了单独开个Issue还是蛮丢人的hhhhh

**Comment by SilveryStar** [comment]
> 能否考虑提供一个Master广播&开发者公告功能，将需要广播的内容对BOT使用指令发送至所有群。

关于公告，我们计划通过 qq频道 来发布，见 #137

**Comment by AzusaYukina** [comment]
指令 `sub rem` 能否添加 `all` 参数一键清除自己订阅的全部材料提醒
由于现在可以直接在群内使用 `today` 指令查询今日全部素材，因此部分用户反馈订阅材料反而变得不方便，希望可以一键删除

**Comment by SilveryStar** [comment]
> 指令 `sub rem` 能否添加 `all` 参数一键清除自己订阅的全部材料提醒 由于现在可以直接在群内使用 `today` 指令查询今日全部素材，因此部分用户反馈订阅材料反而变得不方便，希望可以一键删除

这几天我不太有空，之后加，现在你可以直接删除数据库的字段
```
docker exec -it bot-redis redis-cli
keys silvery-star.daily-sub-*
del silvery-star.daily-sub-要删除的qq号
```

**Comment by AzusaYukina** [comment]
我之前试过了，会变成这样
![% PR(` AE)EO}` 5F1J4(Z8](https://user-images.githubusercontent.com/53286112/145558462-18831c31-4fd5-4aa5-9c29-9c12d9a09ee2.gif)
~~总之就是很离谱~~

**Comment by huzwu** [comment]
大佬，角色培养图鉴 攻略 更新了2.2新版本 https://bbs.mihoyo.com/ys/article/7990798

**Comment by SilveryStar** [comment]
> 大佬，角色培养图鉴 攻略 更新了2.2新版本 https://bbs.mihoyo.com/ys/article/7990798 对了，攻略旅行者name是什么，搜不到名字 ，建议（风主 雷主 岩主）

已更新，旅行者相关图片需要等到12点后或重启bot才能看到

**Comment by canisminor1990** [comment]
建议加入圣遗物 OCR 评分，https://github.com/H-K-Y/Genshin_Impact_bot/commit/9e5eabf7e3f9180014a9d50c3ebbe332d8c788a3

**Comment by SilveryStar** [comment]
> 建议加入圣遗物 OCR 评分，[H-K-Y/Genshin_Impact_bot@9e5eabf](https://github.com/H-K-Y/Genshin_Impact_bot/commit/9e5eabf7e3f9180014a9d50c3ebbe332d8c788a3)

看了，这用的可莉特调的 api，已经非常旧了，新版圣遗物没法识别，更新很慢而且准确度不高，之前本来有打算的最后还是没做

**Comment by Cn7ci4** [comment]
建议查询信息的时候可以查询到圣遗物的套装效果。(感觉工作量又加了很多)

**Comment by SilveryStar** [comment]
> 建议查询信息的时候可以查询到圣遗物的套装效果。(感觉工作量又加了很多)

可不敢，新圣遗物的套装效果令人不敢恭维， 441f288bc2bf81444eb54dc696ba76cbf7ad75d7 这个 fix 就是因为那描述太长了
~~2.3 就这样，以后变成什么样我都不敢想~~

**Comment by deYangar** [comment]
大佬，黑榜现在靠玩家自己投票阵容复活了
所以深渊榜单有复活的打算吗
![QQ截图20211213170717](https://user-images.githubusercontent.com/70438628/145783351-eabe667c-1356-48d4-a98d-30a9a5f064ef.jpg)

**Comment by Annabel0530** [comment]
多连抽图里没有十连那种显示抽卡的玩家
![4ADMUR7A)(ANT8 $LWLB`YQ](https://user-images.githubusercontent.com/40524485/145931408-daf16015-1d94-41da-b2ad-5ffc0933689b.gif)
![77Y{4X98_%`8ZKYDKPR~WSF](https://user-images.githubusercontent.com/40524485/145931465-b40194d4-6401-4c3e-aedc-da32fb6130f1.png)

**Comment by SilveryStar** [comment]
> 大佬，黑榜现在靠玩家自己投票阵容复活了
> 所以深渊榜单有复活的打算吗

再看吧，优先级比较低

**Comment by SilveryStar** [comment]
> 多连抽图里没有十连那种显示抽卡的玩家

下个版本弄吧

**Comment by Annabel0530** [comment]
![F5499CCAAC0C44BCB37187181A0F2415](https://user-images.githubusercontent.com/40524485/145998768-5782c343-65ea-4a21-9865-7c714d9dea63.png)
希望cookie过期的时候可以提醒重新登录米游社获取cookie

**Comment by AzusaYukina** [comment]
`note` 指令的树脂提示可不可以加个选项改为回满的具体时间，感觉十几个小时之后还是不那么直观
~~顺带这个 issue 关了去哪提功能需求啊（悲）~~

**Comment by Accelerator1213** [comment]
您好，您的反馈信息已收到。请确认反馈格式正确。处罚申诉请提供以下信息以便于工作人员进行核实：账号：描述：处罚查询截图：举报请按以下格式提交cfr文件：作弊类型_ID_时间_版本号.cfr例如：踢腿宏_Trinity._20200327_535.cfr销售外挂Q群举报：复制加群链接，一行一个。建议通过腾讯110举报（http://110.qq.com）

**Comment by keaiye** [comment]
建议将help通过渲染图片的方式发送，文字发送显得太乱了

**Comment by imaegoo** [comment]
洞天宝钱已满提醒
