### ISSUE TITLE
怎么转移插件

### ISSUE THREAD

**Issue by Lenhee** [SilveryStar/Adachi-BOT#71]
请问如何将该项目 https://github.com/Arondight/Adachi-BOT 中的部分插件合并到本项目，非常喜欢本项目玩家信息卡片的样式，另外的项目也有很优秀的插件，希望有方法整合在一起

**Comment by SilveryStar** [comment]
两边项目差异较大，只能重写，无法移植。如有需要，可以在 #70 中进行反馈，我会视情况进行整合，并发布在 [插件库](https://github.com/SilveryStar/Adachi-Plugin) 中
