### ISSUE TITLE
【意见征集】是否需要支持可以为每个指令单独设置操作CD

### ISSUE THREAD

**Issue by SilveryStar** [SilveryStar/Adachi-BOT#84]
近期正在对项目进行小范围重构+`WebConsole` 功能的开发，正好征询一下各用户对如题的看法

对于目前的方案，只可以设置群聊和私聊中的操作CD两个数值，缺少粒度更细的控制方案，但是优点在于在CD内可以过滤多余的操作，优化应用性能
如果要支持独立设置，则需要优先定位消息触发的指令才能进行CD判定，较损耗运算资源，大群不友好

### 投票
[![](https://api.gh-polls.com/poll/01FKNEHV69GWEY66VQ5KB31EJQ/需要)](https://api.gh-polls.com/poll/01FKNEHV69GWEY66VQ5KB31EJQ/需要/vote)
[![](https://api.gh-polls.com/poll/01FKNEHV69GWEY66VQ5KB31EJQ/不需要)](https://api.gh-polls.com/poll/01FKNEHV69GWEY66VQ5KB31EJQ/不需要/vote)

**备注:** 只有不少于 2/3 的投票选择 “需要” 时，才会进行此更改
**截止时间:** 11月7日 22:00，若此时投票人数少于 15 人，则延长至人数达到为止

**Comment by VsentCN** [comment]
提示500

**Comment by SilveryStar** [comment]
> 提示500

改好了

**Comment by Autumn-of-One** [comment]
能改成每个QQ号3秒的CD吗。加不加都行，我是小群，用的比较少对于操作CD也无所谓。

**Comment by SilveryStar** [comment]
> 能改成每个QQ号3秒的CD吗。加不加都行，我是小群，用的比较少对于操作CD也无所谓。

可以配置的啊……两个 intervalTime 都改成 3000 就行

**Comment by Autumn-of-One** [comment]
> > 能改成每个QQ号3秒的CD吗。加不加都行，我是小群，用的比较少对于操作CD也无所谓。
> 
> 可以配置的啊……两个 intervalTime 都改成 3000 就行

抱歉，看到了
