### ISSUE TITLE
mys和uid查询头像使用错误或有误导倾向

### ISSUE THREAD

**Issue by Haku247** [SilveryStar/Adachi-BOT#86]
使用mys查询时，查询结果的头像和UID是**被查询人**。
使用uid查询时，查询结果的头像和名称是**查询人**的QQ名称和头像。这可能会造成误导，虽然uid接口里没有头像和名称信息，但在输出图片时，应该把头像和名称隐藏，而不是输出**查询人**的信息。

**Comment by SilveryStar** [comment]
头像的话其实是在已有角色列表里随机的
之后改成 uid 查询不显示昵称吧，等BOT下个版本
