### ISSUE TITLE
关于command.yml

### ISSUE THREAD

**Issue by czw63** [SilveryStar/Adachi-BOT#9]
请问这个command.yml文件有详细的配置教程吗

**Comment by SilveryStar** [comment]
如果你只是想修改命令头，可以参考这个 [repo](https://github.com/Arondight/Adachi-BOT/commit/5d7832c705d5187513031b09b7c6a8a6103f0ab6)，他很好的实现了本地化
如果你想自己增加命令，请学习 [正则表达式](https://m.runoob.com/regexp/regexp-syntax.html) 和 [YAML](https://www.runoob.com/w3cnote/yaml-intro.html)
