### ISSUE TITLE
私人服务提醒出错

### ISSUE THREAD

**Issue by VsentCN** [SilveryStar/Adachi-BOT#92]
### 环境
- 系统：Windows Server 2019 DataCenter 64bitCN
- node 版本：13.13.0
- bot 版本：2.1.13

### 操作复述

运行一段时间后树脂和派遣结束的提醒功能失效，并且树脂在玩家清理之后会发出错误提醒，即设置的树脂满120提醒，查询树脂时有90树脂，消耗20点之后，就会在100点时提醒树脂已满120
### 配置文件

无修改
### 错误报告
无报错

**Comment by oha189** [comment]
中间消耗是没有算的，第一次查询获取到状态，然后直接通过计算定时提醒，没有去再查，除非你在触发查询。
我记得是这样，之前看过一下，没记错的话

**Comment by VsentCN** [comment]
> 中间消耗是没有算的，第一次查询获取到状态，然后直接通过计算定时提醒，没有去再查，除非你在触发查询。 我记得是这样，之前看过一下，没记错的话

可以加一个提醒之前再查询一遍，如果不满足再重新计算设置定时

**Comment by SilveryStar** [comment]
这个其实是已知问题，问就是下个版本修复（
明天就能拿到电脑了，今天晚点开个issue说一下当前的开发进度和已知bug

**Comment by SilveryStar** [comment]
现在改成了整点刷新时间，应该会好些

**Comment by VsentCN** [comment]
> 现在改成了整点刷新时间，应该会好些

我是建议在发出提醒之前再获取一次树脂数判断是否一致
