### ISSUE TITLE
Adachi-BOT v2.2.0 Beta

### ISSUE THREAD

**Issue by SilveryStar** [SilveryStar/Adachi-BOT#93]
体验版 [v2.2.0-Beta1](https://github.com/SilveryStar/Adachi-BOT/tree/web_console_dev)

### Feature
- [x] `Web Console`
  * [x] 前端框架
  * [x] 实时日志
  * [x] 指令使用统计
  * [x] 权限管理
- [x] 数据收集与统计
- [x] 高频使用监测

### Bugfix

- [x] ？`silvery-star.almanac` 在部署环境中发生无限递归爆栈 
- [x] `silvery-star.slip` 概率返回 `undefined`
- [x] 角色数据查询逻辑错误

### Pref
- [x] 优化 `silvery-star.abyss` 和 `silvery-star.uid-query` 在渲染页面的名称显示
- [x] 优化 `NoteService` 的数据更新逻辑

### Refactor
- [x] 重构 BOT 启动逻辑

### BreakChange
- [x] `intervalTime` 被彻底废弃
- [x] v2.1.0 之前的配置不再兼容

**Comment by SilveryStar** [comment]
Web Console Beta UI
<img width="960" alt="Stat" src="https://user-images.githubusercontent.com/42149290/141825712-dd511e4f-8bf8-4ce3-8b67-04da58b04563.png">
<img width="960" alt="Log" src="https://user-images.githubusercontent.com/42149290/141825716-af7dbabe-ad8e-44e7-b009-aa1fcd1f2a16.png">
![User](https://user-images.githubusercontent.com/42149290/141825722-d2524f0d-1960-4f3f-904c-f287399ee040.png)

**Comment by Autumn-of-One** [comment]
> （我知道P3的设计真的巨大丑，欢迎懂UI设计的大佬邮件交流 `silverystar.top@gmail.com`）

按我的直男审美已经可以了

**Comment by yexin9** [comment]
确实，感觉挺好的了

**Comment by Mark9804** [comment]
P3背景色可以改成#fff 或者 #eee，然后阴影的blur给一个大一点的数值，整体观感会比现在好很多

**Comment by SilveryStar** [comment]
> P3背景色可以改成#fff 或者 #eee，然后阴影的blur给一个大一点的数值，整体观感会比现在好很多

背景色都是统一的 #f1f1f1，单一个页面的修改的话违和感比较强（而且说实话也不太好单独改），把 shadow 调低然后调高 blur 确实会好些，不过主要问题还是在于布局

**Comment by deYangar** [comment]
切换到日志那里时，能默认显示到今天的最底下吗，现在从其他版块切换过去是手动选日期然后拉到最底下

**Comment by SilveryStar** [comment]
> 切换到日志那里时，能默认显示到今天的最底下吗，现在从其他版块切换过去是手动选日期然后拉到最底下

如果选择了当天就自动拉到最底部这个之后回补上，不过进入页面自动选择当天这个暂时没打算改，因为日志这个数据传输量比统计大得多，而且选择当天还会开启ws连接，在页面加载完成前进行的话渲染可能容易出问题，还是保留选择日期这一步比较好
