### ISSUE TITLE
抽签时，部分用户回复undefined，无错误报告

### ISSUE THREAD

**Issue by deYangar** [SilveryStar/Adachi-BOT#94]
### 环境
- 系统：Windows 10 1909
- node 版本：13.13.0
- bot 版本：2.1.13

### 操作复述
抽签时，部分用户回复undefined。只有部分用户会出现此情况。

![QQ图片20211117005909](https://user-images.githubusercontent.com/70438628/142030570-273f0c65-987f-4326-8950-94f3055ad31f.png)

### 配置文件
仅修改过commands，修改命令为中文

### 错误报告
无错误报告

**Comment by SilveryStar** [comment]
此bug在2.2.0-beta1中（应该）已经修复了，请前往 web_console_dev 下载最新版本
