### ISSUE TITLE
使用Linux时老是碰到的问题

### ISSUE THREAD

**Issue by Autumn-of-One** [SilveryStar/Adachi-BOT#97]
### 环境
- 系统：CentOS7.6-Docker20
- node 版本：v13.13.0
- bot 版本：v2.0

### 操作复述

`[root@VM-16-16-centos ~]# cd /root/Adachi-BOT-1/
[root@VM-16-16-centos Adachi-BOT-1]# mkdir config && cd config
[root@VM-16-16-centos config]# touch setting.yml commands.yml cookies.yml
[root@VM-16-16-centos config]# cd .
[root@VM-16-16-centos config]# cd ..
[root@VM-16-16-centos Adachi-BOT-1]# npm install

> puppeteer@10.0.0 install /root/Adachi-BOT-1/node_modules/puppeteer
> node install.js

ERROR: Failed to set up Chromium r884014! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
[Error: EACCES: permission denied, mkdir '/root/Adachi-BOT-1/node_modules/puppeteer/.local-chromium'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/root/Adachi-BOT-1/node_modules/puppeteer/.local-chromium'
}
npm WARN adachi-bot@2.1.13 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/forever-monitor/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@10.0.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@10.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-17T14_43_43_314Z-debug.log
`
### 配置文件

无
### 错误报告
之前我一直都用的windows，但目前新的项目可能对Windows不太又好，本人又是个小白，就尝试使用Linux，但每次都卡在这里，希望作者帮忙看看，拜谢。

**Comment by SilveryStar** [comment]
尝试一下 `sudo npm install --unsafe-perm=true --allow-root`

**Comment by SilveryStar** [comment]
另外最新的版本需要通过 `git clone https://github.com.cnpmjs.org/SilveryStar/Adachi-BOT.git -b web_console_dev` 来下载，你这里还是 v2.1.13

**Comment by Autumn-of-One** [comment]
> 另外最新的版本需要通过 `git clone https://github.com.cnpmjs.org/SilveryStar/Adachi-BOT.git -b web_console_dev` 来下载，你这里还是 v2.1.13

最新的版本我在Windows上测试过了，跟那位老哥一样的问题，无法通过forever启动，所以我打算在docker版本稳定后使用docker，但我docker也没用过，现在是在旧版本练手。

**Comment by SilveryStar** [comment]
那既然你是 docker 启动的话，是不需要 install 所有包的，按照**启动**里的步骤走应该是不会出问题的

**Comment by Autumn-of-One** [comment]
> 另外最新的版本需要通过 `git clone https://github.com.cnpmjs.org/SilveryStar/Adachi-BOT.git -b web_console_dev` 来下载，你这里还是 v2.1.13

这次我尝试新版本，这是我的控制台操作。程序好像启动了，CPU占用也到了70，但是访问不了。麻烦作者看看是什么问题，谢谢。

`[root@VM-16-16-centos ~]# git clone https://github.com.cnpmjs.org/SilveryStar/Adachi-BOT.git -b web_console_dev`
Cloning into 'Adachi-BOT'...
remote: Enumerating objects: 2403, done.
remote: Counting objects: 100% (1285/1285), done.
remote: Compressing objects: 100% (897/897), done.
remote: Total 2403 (delta 727), reused 865 (delta 377), pack-reused 1118
Receiving objects: 100% (2403/2403), 52.98 MiB | 3.53 MiB/s, done.
Resolving deltas: 100% (1097/1097), done.

`[root@VM-16-16-centos ~]# cd Adachi-BOT`

`[root@VM-16-16-centos Adachi-BOT]# npm install`
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

#> puppeteer@10.0.0 install /root/Adachi-BOT/node_modules/puppeteer
#> node install.js

ERROR: Failed to set up Chromium r884014! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
[Error: EACCES: permission denied, mkdir '/root/Adachi-BOT/node_modules/puppeteer/.local-chromium'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/root/Adachi-BOT/node_modules/puppeteer/.local-chromium'
}
npm WARN adachi-bot@2.2.0-Beta2 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/forever-monitor/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@10.0.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@10.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-18T09_31_58_106Z-debug.log

`[root@VM-16-16-centos Adachi-BOT]# sudo npm install --unsafe-perm=true --allow-root`
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

#> puppeteer@10.0.0 install /root/Adachi-BOT/node_modules/puppeteer
#> node install.js

Downloading Chromium r884014 - 138.7 Mb [====================] 99% 0.0s
Chromium (884014) downloaded to /root/Adachi-BOT/node_modules/puppeteer/.local-chromium/linux-884014
npm WARN adachi-bot@2.2.0-Beta2 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/forever-monitor/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 37 packages from 22 contributors and audited 620 packages in 19.129s

44 packages are looking for funding
  run `npm fund` for details

found 7 vulnerabilities (6 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

`[root@VM-16-16-centos Adachi-BOT]# npm run start`

> adachi-bot@2.2.0-Beta2 start /root/Adachi-BOT
> ts-node -r tsconfig-paths/register app.ts --files

====================================================================
                _            _     _        ____   ____ _______
       /\      | |          | |   (_)      |  _ \ / __ \__   __|
      /  \   __| | __ _  ___| |__  _ ______| |_) | |  | | | |
     / /\ \ / _` |/ _` |/ __| '_ \| |______|  _ <| |  | | | |
    / ____ \ (_| | (_| | (__| | | | |      | |_) | |__| | | |
   /_/    \_\__,_|\__,_|\___|_| |_|_|      |____/ \____/  |_|

====================================================================
环境初始化完成，请在 /config 文件夹中配置信息

`[root@VM-16-16-centos Adachi-BOT]# npm run serve`
> adachi-bot@2.2.0-Beta2 serve /root/Adachi-BOT
> forever start --minUptime 1000 --spinSleepTime 1000 -v -c "npm run start" ./
info:    Forever processing file: ./

`[root@VM-16-16-centos Adachi-BOT]# forever list`
info:    Forever processes running
data:        uid  command       script forever pid   id logfile                 uptime
data:    [0] en0G npm run start        11407   12430    /root/.forever/en0G.log 0:0:0:3.924

`[root@VM-16-16-centos Adachi-BOT]# curl localhost`
curl: (7) Failed connect to localhost:80; Connection refused

**Comment by SilveryStar** [comment]
你把 `/root/.forever/en0G.log` 里的内容发出来，记得用[代码块](https://www.runoob.com/markdown/md-code.html)包裹

**Comment by Autumn-of-One** [comment]
我把log发你邮箱`silverystar.top@gmail.com`吧，有点多

**Comment by SilveryStar** [comment]
（邮件被当成垃圾给拦截了）你 redis 没启动，forever redis要独立启动

**Comment by Autumn-of-One** [comment]
我应该已经启动了。

`[root@VM-16-16-centos Adachi-BOT]# forever list`
info:    No forever processes running

`[root@VM-16-16-centos Adachi-BOT]# ps -ef | grep redis`
polkitd   6315  6296  0 19:20 ?        00:00:00 redis-server *:56379
root      7892  1009  0 19:22 pts/0    00:00:00 grep --color=auto redis

```
[root@VM-16-16-centos Adachi-BOT]# cd /root/redis/redis-redis/bin/
[root@VM-16-16-centos bin]# ./redis-server /root/redis/redis-redis/bin/redis.conf
```
`[root@VM-16-16-centos bin]# ps -ef | grep redis`
polkitd   6315  6296  0 19:20 ?        00:00:00 redis-server *:56379
root      8933     1  0 19:24 ?        00:00:00 ./redis-server 127.0.0.1:6379   **#这里应该表示启动成功了**
root      9026  1009  0 19:24 pts/0    00:00:00 grep --color=auto redis
```
[root@VM-16-16-centos bin]# cd /root/Adachi-BOT/
[root@VM-16-16-centos Adachi-BOT]# npm run serve
```
-> adachi-bot@2.2.0-Beta2 serve /root/Adachi-BOT
-> forever start --minUptime 1000 --spinSleepTime 1000 -v -c "npm run start" ./
info:    Forever processing file: ./

`[root@VM-16-16-centos Adachi-BOT]# forever list`
info:    Forever processes running
data:           uid       command       script   forever pid    id            logfile                          uptime
data:    [0] EFSo   npm run start                   9696        9776    /root/.forever/EFSo.log    0:0:0:2.199

**Comment by SilveryStar** [comment]
那你也是在 6379 端口啊，BOT 连接的是 56379 端口，要么重新启动一个，要么改 setting.yml 的 dbPort

**Comment by Autumn-of-One** [comment]
抱歉，之前用代码块的时候，不知道为什么，代码只用一对`'ABC'`包裹而不是用`'''ABC'''`，预览效果很差，只能这么用了，以后会注意。
现在已经连接上了。
