### ISSUE TITLE
托马的攻略更新了，大佬有空的话能更新一下吗

### ISSUE THREAD

**Issue by deYangar** [SilveryStar/Adachi-BOT#98]
### 环境
- 系统：Windows 10 1909专业版
- node 版本：13.13.0
- bot 版本：2.1.13

### 操作复述
https://bbs.mihoyo.com/ys/article/11524093
![12640594978d8291c029794128be8630_898583602489478942](https://user-images.githubusercontent.com/70438628/142374407-8d64de93-f223-4e09-bb6e-129817280773.png)

### 错误报告
[2021-11-18T15:48:39.961] [WARN] [Android:1563077598] - 图片下载失败: http status code: 404 (https://adachi-bot.oss-cn-beijing.aliyuncs.com/Version2/guide/托马.png)

**Comment by SilveryStar** [comment]
原本的计划是版本更新前一周的周三更新下版本的内容的，这两天太忙给忘了，晚上应该会更新所有2.3的信息

**Comment by deYangar** [comment]
> 原本的计划是版本更新前一周的周三更新下版本的内容的，这两天太忙给忘了，晚上应该会更新所有2.3的信息

嗷，好的好的，感谢

**Comment by SilveryStar** [comment]
托马和2.3新内容均已更新，部分内容需等12点后bot自动更新配置才能查看
